globalThis.COSMIC_GEMINI_CATALOG = {
  'en-US': {
    appName: 'Cosmic Gemini',
    nativeScrollName: 'Native Scroll',
    noAutoplayName: 'No Autoplay',
    anyCopyName: 'Any Copy',
    videoDownloadName: 'Video Download',
    satellitesName: 'Satellites',
    featureOnTitle: '{product} is on · Click to turn off',
    featureOffTitle: '{product} is off · Click to turn on',
    standardSiteTitle: 'Standard on this site · Click for Enhanced',
    enhancedSiteTitle: 'Enhanced on this site · Click for Standard',
    enhancedCoveredTitle: 'Enhanced mode is set by {rule} · Manage in Settings',
    enhancedUnavailableTitle: 'Remove this site from the whitelist before using Enhanced mode',
    anyCopyOffTitle: 'Enable Any Copy on this site',
    anyCopyOnTitle: 'Any Copy is active on this site · Click to turn off',
    anyCopyCoveredTitle: 'Any Copy is enabled by {rule} · Manage in Settings',
    anyCopyEnhancedOffTitle: 'Open this site in Enhanced Any Copy',
    anyCopyEnhancedOnTitle: 'Enhanced Any Copy is active · Click to exit',
    videoStartTitle: 'Find videos in this tab',
    videoOpenTitle: 'Open videos found in this tab',
    videoStopTitle: 'Stop Video Download in this tab',
    videoRescanTitle: 'Scan this tab again',
    addWhitelistTitle: 'Add this site to the {product} whitelist',
    removeWhitelistTitle: 'Remove this site from the {product} whitelist',
    coveredWhitelistTitle: 'Covered by {rule} · Manage in Settings',
    unsupportedTitle: 'This page is unavailable',
    settingsTitle: 'Open {product} settings',
    popupLabel: 'Cosmic Gemini controls',
    settingsHeading: 'Settings',
    switchNativeSettings: 'Open Native Scroll settings',
    switchAutoplaySettings: 'Open No Autoplay settings',
    switchAnyCopySettings: 'Open Any Copy settings',
    switchVideoDownloadSettings: 'Open Video Download settings',
    switchSatellitesSettings: 'Open Satellites settings',
    nativeStandardHeading: 'Native Scroll – Standard mode',
    autoplayStandardHeading: 'No Autoplay – Standard mode',
    nativeProtectionHelp: 'Keep browser scrolling in control across websites.',
    autoplayProtectionHelp: 'Stop video and audio that starts without your action.',
    enhancedSitesHeading: 'Enhanced mode sites',
    nativeEnhancedSitesHelp: 'Use broader scroll protection only on matching websites.',
    autoplayEnhancedSitesHelp: 'Remove video and audio elements on matching websites, including media added later.',
    anyCopyEnhancedSitesHelp: 'Rebuild matching pages as clean, static reading views with selectable text and unobstructed images.',
    enforcedSitesHeading: 'Standard mode sites',
    enforcedSitesHelp: 'Any Copy restores selection and preserves the text you copy on matching websites.',
    whitelistHeading: 'Whitelist',
    nativeWhitelistHelp: 'Native Scroll stays inactive on matching websites.',
    autoplayWhitelistHelp: 'No Autoplay stays inactive on matching websites.',
    audioAllowHeading: 'Always allow sound autoplay',
    audioAllowHelp: 'Allow audio elements and Web Audio to start automatically on matching websites. Autoplaying videos remain blocked.',
    anyCopyStandardHeading: 'Any Copy – Standard mode',
    siteActivationLabel: 'Site activation',
    anyCopyActivationHelp: 'Enable Any Copy for the current website from the extension popup. Exact hostnames are saved by default; wildcard rules can be added below.',
    rulePlaceholder: 'example.com or *.example.com',
    add: 'Add',
    removeRule: 'Remove {rule}',
    emptyEnhancedSites: 'No websites use Enhanced mode.',
    emptyEnforcedSites: 'Any Copy is not enabled on any website.',
    emptyWhitelist: 'No websites have been added.',
    emptyAudioAllow: 'No websites may autoplay sound.',
    exactRuleHelp: 'example.com matches that hostname only. *.example.com also matches the root domain and all of its subdomains.',
    invalidRule: 'Enter a valid hostname or a wildcard such as *.example.com.',
    duplicateRule: 'That rule is already listed.',
    languageHeading: 'Language',
    english: 'English',
    chinese: '简体中文',
    helpHeading: 'How it works',
    nativeHelpStandard: 'Native Scroll intercepts website code that takes over wheel and trackpad gestures in Standard mode while preserving ordinary page controls and scrollable areas.',
    nativeHelpEnhanced: 'Enhanced mode also handles pages that simulate movement or repeatedly restore custom scrolling. It applies only to websites you add to Enhanced mode sites.',
    nativeHelpIndicator: 'The toolbar icon changes after Native Scroll suppresses scrolling code on the current page.',
    autoplayHelpStandard: 'No Autoplay stops media that starts without a direct action. Media you intentionally play remains available.',
    autoplayHelpEnhanced: 'Enhanced mode removes video and audio elements from websites you add to Enhanced mode sites.',
    autoplayHelpSound: 'When a website tries to autoplay sound, you can keep blocking it, allow it temporarily, or always allow sound for that website.',
    anyCopyHelpStandard: 'Any Copy restores text selection, keeps copy shortcuts available, and prevents websites from replacing copied content or adding promotional text.',
    anyCopyHelpEnhanced: 'Enhanced mode places a static reading view over the original page. Leaving Enhanced mode restores the original page immediately.',
    videoDownloadActivationHelp: 'Open the extension popup and click Video Download to find downloadable media in the current tab.',
    clickToEnableLabel: 'Click to enable',
    videoDownloadPreferencesHeading: 'Download preferences',
    videoDownloadPreferencesHelp: 'Choose how Video Download selects streams and starts Chrome downloads.',
    preferredQualityHeading: 'Preferred quality',
    preferredQualityHelp: 'The closest available quality is used when a stream offers several variants.',
    qualityBest: 'Best available',
    askWhereToSaveHeading: 'Ask where to save',
    askWhereToSaveHelp: 'Show Chrome’s save dialog before each file is downloaded.',
    videoDownloadHelpDetection: 'Video Download combines network requests, player state, streaming manifests, embedded frames, and dedicated support for compatible video services.',
    videoDownloadHelpFormats: 'Direct files, compatible HLS and DASH streams, separate video and audio tracks, subtitles, and live snapshots are processed locally. Standard AES-128 HLS and supported wrapped HLS playlists are also handled.',
    videoDownloadHelpSession: 'Detection applies only to the current tab. It continues through same-site navigation and ends when the tab changes to another website, closes, or you stop it.',
    videoDownloadPrivacy: 'Video Download keeps detected media information only for the active tab session and does not save browsing or download history. Selected media is fetched from its source and processed locally.',
    back: 'Back',
    download: 'Download',
    videoScanningHelp: 'Looking for video. If nothing appears, play the video once and reopen this panel.',
    videoUnavailablePage: 'Video Download cannot inspect this page.',
    videoStopped: 'Video Download has stopped in this tab.',
    videoFound: 'Formats found: {count}',
    otherFormats: 'Other formats ({count})',
    videoStream: 'HLS stream',
    videoCombinedStream: 'Video + audio',
    videoDashStream: 'DASH stream',
    videoSubtitles: 'Subtitles',
    videoProtectedMedia: 'Protected media',
    videoFile: 'Video file',
    videoLiveSnapshot: 'Current live segment window',
    videoUnavailableFormat: 'Unavailable',
    videoPreparing: 'Preparing {progress}%',
    videoDownloading: 'Downloading',
    videoDownloaded: 'Downloaded',
    videoRetry: 'Retry',
    videoDownloadFailedHelp: 'The selected video could not be downloaded.',
    biliDailyLoginName: 'Bili Daily Login',
    satellitesHelpHeading: 'About Satellites',
    satellitesHelpIntro: 'Satellites is a collection of small, optional tools that handle useful background tasks without adding controls to the popup. Each Satellite can be enabled independently, with its purpose and data use explained in its own card.',
    satellitesOverviewHelp: 'Choose the small background tools you want Cosmic Gemini to handle for you.',
    biliDailyLoginDescription: 'Bilibili gives every signed-in account one coin when it visits each day. Bili Daily Login schedules that visit for 00:05 China Standard Time. If Chrome or the computer is not running then, one current-day task catches up the next time Chrome can run; missed days are never replayed.',
    biliDailyLoginPrivacyHeading: 'Privacy',
    biliDailyLoginPrivacy: 'This feature does not inspect whether or when you open Bilibili. Its background schedule contacts Bilibili only while Chrome and the computer are running and Chrome does not report offline, uses the account already signed in to Chrome, never reads or stores your password, and permanently stores only its switch state and last completed date.',
    privacyHeading: 'Privacy',
    nativePrivacy: 'Native Scroll runs locally. It stores only its switch state and the website rules you choose, and does not send browsing data.',
    autoplayPrivacy: 'No Autoplay runs locally. It stores only its switch state, the website rules you choose, and valid temporary sound allowances; temporary allowances are deleted automatically.',
    anyCopyPrivacy: 'Any Copy runs locally. It stores only the website rules you choose and does not send copied text or browsing data.',
    version: 'Version {version}',
    unavailable: 'Unable to update Cosmic Gemini.'
  },
  'zh-CN': {
    appName: 'Cosmic Gemini',
    nativeScrollName: 'Native Scroll',
    noAutoplayName: 'No Autoplay',
    anyCopyName: 'Any Copy',
    videoDownloadName: 'Video Download',
    satellitesName: 'Satellites',
    featureOnTitle: '{product} 已开启 · 点击关闭',
    featureOffTitle: '{product} 已关闭 · 点击开启',
    standardSiteTitle: '当前网站使用标准模式 · 点击改为强力模式',
    enhancedSiteTitle: '当前网站使用强力模式 · 点击改为标准模式',
    enhancedCoveredTitle: '规则 {rule} 已为当前网站开启强力模式 · 前往设置管理',
    enhancedUnavailableTitle: '请先将当前网站移出白名单，再开启强力模式',
    anyCopyOffTitle: '在当前网站开启 Any Copy',
    anyCopyOnTitle: 'Any Copy 正在当前网站运行 · 点击关闭',
    anyCopyCoveredTitle: '规则 {rule} 已为当前网站开启 Any Copy · 前往设置管理',
    anyCopyEnhancedOffTitle: '使用 Any Copy 强力模式打开当前网站',
    anyCopyEnhancedOnTitle: 'Any Copy 强力模式正在运行 · 点击退出',
    videoStartTitle: '查找当前标签页中的视频',
    videoOpenTitle: '查看当前标签页中找到的视频',
    videoStopTitle: '停止在当前标签页中查找视频',
    videoRescanTitle: '重新扫描当前标签页',
    addWhitelistTitle: '将当前网站加入 {product} 白名单',
    removeWhitelistTitle: '将当前网站移出 {product} 白名单',
    coveredWhitelistTitle: '当前网站已由规则 {rule} 加入白名单 · 前往设置管理',
    unsupportedTitle: '当前页面不支持此操作',
    settingsTitle: '打开 {product} 设置',
    popupLabel: 'Cosmic Gemini 控制项',
    settingsHeading: '设置',
    switchNativeSettings: '打开 Native Scroll 设置',
    switchAutoplaySettings: '打开 No Autoplay 设置',
    switchAnyCopySettings: '打开 Any Copy 设置',
    switchVideoDownloadSettings: '打开 Video Download 设置',
    switchSatellitesSettings: '打开 Satellites 设置',
    nativeStandardHeading: 'Native Scroll – 标准模式',
    autoplayStandardHeading: 'No Autoplay – 标准模式',
    nativeProtectionHelp: '阻止网页接管滚动操作，保留 Chrome 原生的滚动体验。',
    autoplayProtectionHelp: '阻止网页在未经您操作的情况下播放视频或声音。',
    enhancedSitesHeading: '强力模式网站',
    nativeEnhancedSitesHelp: '仅在符合规则的网站上使用范围更广的滚动保护。',
    autoplayEnhancedSitesHelp: '移除符合规则的网站中的视频和音频元素，之后新增的媒体也会被移除。',
    anyCopyEnhancedSitesHelp: '将符合规则的网页整理为简洁的静态阅读页面，文字可自由选择，图片也不会被遮挡。',
    enforcedSitesHeading: '标准模式网站',
    enforcedSitesHelp: 'Any Copy 会在符合规则的网站上恢复文字选择，并确保复制内容不被网页篡改。',
    whitelistHeading: '白名单',
    nativeWhitelistHelp: 'Native Scroll 不会在符合规则的网站上运行。',
    autoplayWhitelistHelp: 'No Autoplay 不会在符合规则的网站上运行。',
    audioAllowHeading: '始终允许自动播放声音',
    audioAllowHelp: '允许符合规则的网站自动播放音频元素和 Web Audio。自动播放的视频仍会被拦截。',
    anyCopyStandardHeading: 'Any Copy – 标准模式',
    siteActivationLabel: '按网站启用',
    anyCopyActivationHelp: '请在插件控制窗口中为当前网站开启 Any Copy。插件默认保存当前主机名，您也可以在下方添加通配规则。',
    rulePlaceholder: 'example.com 或 *.example.com',
    add: '添加',
    removeRule: '移除 {rule}',
    emptyEnhancedSites: '尚未为任何网站开启强力模式。',
    emptyEnforcedSites: '尚未在任何网站上开启 Any Copy。',
    emptyWhitelist: '尚未添加任何网站。',
    emptyAudioAllow: '尚未允许任何网站自动播放声音。',
    exactRuleHelp: 'example.com 仅匹配该主机名。*.example.com 同时匹配根域名及其所有子域名。',
    invalidRule: '请输入有效的主机名，或使用 *.example.com 这样的通配规则。',
    duplicateRule: '该规则已在列表中。',
    languageHeading: '语言',
    english: 'English',
    chinese: '简体中文',
    helpHeading: '工作方式',
    nativeHelpStandard: 'Native Scroll 在标准模式下会拦截网页对滚轮和触控板手势的接管，同时保留普通页面控件和可滚动区域的正常操作。',
    nativeHelpEnhanced: '强力模式还会处理模拟页面移动或反复恢复自定义滚动的网页，并且仅在您指定的网站上启用。',
    nativeHelpIndicator: 'Native Scroll 在当前页面拦截滚动代码后，工具栏图标会随之变化。',
    autoplayHelpStandard: 'No Autoplay 会阻止未经您操作便开始播放的媒体。您主动播放的内容仍可正常使用。',
    autoplayHelpEnhanced: '强力模式会从您指定的网站中移除视频和音频元素。',
    autoplayHelpSound: '网站尝试自动播放声音时，您可以继续拦截、本次允许或永久允许该网站播放声音。',
    anyCopyHelpStandard: 'Any Copy 会恢复文字选择和复制快捷键，并阻止网页替换复制内容或添加推广文字。',
    anyCopyHelpEnhanced: '强力模式会在原网页上方生成静态阅读页面。退出强力模式后，原网页会立即恢复。',
    videoDownloadActivationHelp: '请打开插件控制窗口，点击 Video Download 查找当前标签页中可以下载的视频。',
    clickToEnableLabel: '点击启用',
    videoDownloadPreferencesHeading: '下载设置',
    videoDownloadPreferencesHelp: '设置 Video Download 选择视频流和开始下载时使用的方式。',
    preferredQualityHeading: '首选画质',
    preferredQualityHelp: '视频流提供多种画质时，插件会选择最接近该设置的一项。',
    qualityBest: '最高可用画质',
    askWhereToSaveHeading: '下载前选择保存位置',
    askWhereToSaveHelp: '每次下载前显示 Chrome 的文件保存窗口。',
    videoDownloadHelpDetection: 'Video Download 会综合分析网络请求、播放器状态、视频流清单和嵌入式页面，并针对兼容的视频服务进行识别。',
    videoDownloadHelpFormats: '插件会在本地处理视频文件、兼容的 HLS 与 DASH 视频流、分离的音视频轨道、字幕和直播片段，也支持标准 AES-128 HLS 与部分经过封装的 HLS 清单。',
    videoDownloadHelpSession: '视频查找仅在当前标签页中启用。站内跳转不会中断，前往其他网站、关闭标签页或手动停止后会自动结束。',
    videoDownloadPrivacy: 'Video Download 只会在当前标签页的临时会话中保留检测到的媒体信息，不会保存浏览记录或下载历史。选中的媒体会从原网站获取，并在本地完成处理。',
    back: '返回',
    download: '下载',
    videoScanningHelp: '正在查找视频。如果没有出现结果，请播放一次视频后重新打开此页面。',
    videoUnavailablePage: 'Video Download 无法检查当前页面。',
    videoStopped: '已停止在当前标签页中查找视频。',
    videoFound: '已找到 {count} 种格式',
    otherFormats: '其他格式（{count}）',
    videoStream: 'HLS 视频流',
    videoCombinedStream: '视频与音频',
    videoDashStream: 'DASH 视频流',
    videoSubtitles: '字幕',
    videoProtectedMedia: '受保护媒体',
    videoFile: '视频文件',
    videoLiveSnapshot: '当前直播片段',
    videoUnavailableFormat: '暂不支持',
    videoPreparing: '正在处理 {progress}%',
    videoDownloading: '正在下载',
    videoDownloaded: '下载完成',
    videoRetry: '重试',
    videoDownloadFailedHelp: '无法下载所选视频。',
    biliDailyLoginName: 'Bili Daily Login',
    satellitesHelpHeading: '关于 Satellites',
    satellitesHelpIntro: 'Satellites 汇集了一些无需占用控制窗口的小功能，用于完成实用的后台任务。每项功能都可以独立开启，其用途和数据处理方式会直接写在对应的设置卡片中。',
    satellitesOverviewHelp: '您可以在这里选择需要 Cosmic Gemini 在后台完成的小功能。',
    biliDailyLoginDescription: '哔哩哔哩每天会向访问网站的登录账号发放一枚硬币。Bili Daily Login 按北京时间每天 00:05 安排访问。若当时 Chrome 未运行或电脑处于休眠状态，则在 Chrome 下次可以运行时仅补做当天任务，不追补此前错过的日期。',
    biliDailyLoginPrivacyHeading: '隐私',
    biliDailyLoginPrivacy: '本功能不会判断或记录您是否、何时打开哔哩哔哩。后台日程仅在电脑已唤醒、Chrome 正在运行且未报告离线时访问哔哩哔哩服务，直接使用 Chrome 中已有的登录状态，不读取或保存密码。长期保存的内容仅包括功能开关和最近一次完成日期。',
    privacyHeading: '隐私',
    nativePrivacy: 'Native Scroll 完全在本地运行，仅保存功能开关和您选择的网站规则，不会发送浏览数据。',
    autoplayPrivacy: 'No Autoplay 完全在本地运行，仅保存功能开关、您选择的网站规则和仍然有效的临时声音权限。临时权限到期后会自动删除。',
    anyCopyPrivacy: 'Any Copy 完全在本地运行，仅保存您选择的网站规则，不会发送复制内容或浏览数据。',
    version: '版本 {version}',
    unavailable: 'Cosmic Gemini 暂时无法更新设置。'
  }
};
