globalThis.COSMIC_GEMINI_CATALOG = {
  'en-US': {
    appName: 'Cosmic Gemini',
    nativeScrollName: 'Native Scroll',
    noAutoplayName: 'No Autoplay',
    anyCopyName: 'Any Copy',
    featureOnTitle: '{product} is on · Click to turn off',
    featureOffTitle: '{product} is off · Click to turn on',
    standardSiteTitle: 'Standard on this site · Click for Enhanced',
    enhancedSiteTitle: 'Enhanced on this site · Click for Standard',
    enhancedCoveredTitle: 'Enhanced mode is set by {rule} · Manage in Settings',
    enhancedUnavailableTitle: 'Remove this site from the whitelist before using Enhanced mode',
    anyCopyOffTitle: 'Enable Any Copy on this site',
    anyCopyOnTitle: 'Any Copy is active on this site · Click to turn off',
    anyCopyCoveredTitle: 'Any Copy is enabled by {rule} · Manage in Settings',
    anyCopyEnhancedOffTitle: 'Open this site in Enhanced Any Copy',
    anyCopyEnhancedOnTitle: 'Enhanced Any Copy is active · Click to exit',
    addWhitelistTitle: 'Add this site to the {product} whitelist',
    removeWhitelistTitle: 'Remove this site from the {product} whitelist',
    coveredWhitelistTitle: 'Covered by {rule} · Manage in Settings',
    unsupportedTitle: 'This page is unavailable',
    settingsTitle: 'Open {product} settings',
    popupLabel: 'Cosmic Gemini controls',
    settingsHeading: 'Settings',
    switchNativeSettings: 'Open Native Scroll settings',
    switchAutoplaySettings: 'Open No Autoplay settings',
    switchAnyCopySettings: 'Open Any Copy settings',
    protectionHeading: 'Protection',
    nativeProtectionHelp: 'Keep browser scrolling in control across websites.',
    autoplayProtectionHelp: 'Stop video and audio that starts without your action.',
    enhancedSitesHeading: 'Enhanced sites',
    nativeEnhancedSitesHelp: 'Use broader scroll protection only on matching websites.',
    autoplayEnhancedSitesHelp: 'Remove video and audio elements on matching websites, including media added later.',
    anyCopyEnhancedSitesHelp: 'Rebuild matching pages as clean, static reading views with selectable text and unobstructed images.',
    enforcedSitesHeading: 'Enforced sites',
    enforcedSitesHelp: 'Any Copy restores selection and preserves the text you copy on matching websites.',
    whitelistHeading: 'Whitelist',
    nativeWhitelistHelp: 'Native Scroll stays inactive on matching websites.',
    autoplayWhitelistHelp: 'No Autoplay stays inactive on matching websites.',
    audioAllowHeading: 'Always allow sound autoplay',
    audioAllowHelp: 'Allow audio elements and Web Audio to start automatically on matching websites. Autoplaying videos remain blocked.',
    anyCopyActivationHeading: 'Site activation',
    anyCopyActivationHelp: 'Enable Any Copy for the current website from the extension popup. Exact hostnames are saved by default; wildcard rules can be added below.',
    rulePlaceholder: 'example.com or *.example.com',
    add: 'Add',
    removeRule: 'Remove {rule}',
    emptyEnhancedSites: 'No websites use Enhanced mode.',
    emptyEnforcedSites: 'Any Copy is not enabled on any website.',
    emptyWhitelist: 'No websites have been added.',
    emptyAudioAllow: 'No websites may autoplay sound.',
    exactRuleHelp: 'example.com matches that hostname only. *.example.com also matches the root domain and all of its subdomains.',
    invalidRule: 'Enter a valid hostname or a wildcard such as *.example.com.',
    duplicateRule: 'That rule is already listed.',
    languageHeading: 'Language',
    nativeLanguageHelp: 'Choose the language used by Cosmic Gemini.',
    autoplayLanguageHelp: 'Choose the language used by Cosmic Gemini.',
    anyCopyLanguageHelp: 'Choose the language used by Cosmic Gemini.',
    english: 'English',
    chinese: '简体中文',
    helpHeading: 'How it works',
    nativeHelpStandard: 'Standard protection intercepts website code that takes over wheel and trackpad gestures while preserving ordinary page controls and scrollable areas.',
    nativeHelpEnhanced: 'Enhanced protection also handles pages that simulate movement or repeatedly restore custom scrolling. It applies only to websites you add to Enhanced sites.',
    nativeHelpIndicator: 'The toolbar icon changes after Native Scroll suppresses scrolling code on the current page.',
    autoplayHelpStandard: 'No Autoplay stops media that starts without a direct action. Media you intentionally play remains available.',
    autoplayHelpEnhanced: 'Enhanced protection removes video and audio elements from websites you add to Enhanced sites.',
    autoplayHelpSound: 'When a website tries to autoplay sound, you can keep blocking it, allow it temporarily, or always allow sound for that website.',
    anyCopyHelpStandard: 'Any Copy restores text selection, keeps copy shortcuts available, and prevents websites from replacing copied content or adding promotional text.',
    anyCopyHelpEnhanced: 'Enhanced mode places a static reading view over the original page. Leaving Enhanced mode restores the original page immediately.',
    privacyHeading: 'Privacy',
    privacyText: 'Cosmic Gemini runs locally and makes no network requests. It stores only your settings and the website rules you choose; temporary sound allowances are deleted automatically.',
    version: 'Version {version}',
    unavailable: 'Unable to update Cosmic Gemini.'
  },
  'zh-CN': {
    appName: 'Cosmic Gemini',
    nativeScrollName: 'Native Scroll',
    noAutoplayName: 'No Autoplay',
    anyCopyName: 'Any Copy',
    featureOnTitle: '{product} 已开启 · 点击关闭',
    featureOffTitle: '{product} 已关闭 · 点击开启',
    standardSiteTitle: '当前网站使用标准模式 · 点击改为增强模式',
    enhancedSiteTitle: '当前网站使用增强模式 · 点击改为标准模式',
    enhancedCoveredTitle: '规则 {rule} 已为当前网站开启增强模式 · 前往设置管理',
    enhancedUnavailableTitle: '请先将当前网站移出白名单，再开启增强模式',
    anyCopyOffTitle: '在当前网站开启 Any Copy',
    anyCopyOnTitle: 'Any Copy 正在当前网站运行 · 点击关闭',
    anyCopyCoveredTitle: '规则 {rule} 已为当前网站开启 Any Copy · 前往设置管理',
    anyCopyEnhancedOffTitle: '使用 Any Copy 增强模式打开当前网站',
    anyCopyEnhancedOnTitle: 'Any Copy 增强模式正在运行 · 点击退出',
    addWhitelistTitle: '将当前网站加入 {product} 白名单',
    removeWhitelistTitle: '将当前网站移出 {product} 白名单',
    coveredWhitelistTitle: '当前网站已由规则 {rule} 加入白名单 · 前往设置管理',
    unsupportedTitle: '当前页面不支持此操作',
    settingsTitle: '打开 {product} 设置',
    popupLabel: 'Cosmic Gemini 控制项',
    settingsHeading: '设置',
    switchNativeSettings: '打开 Native Scroll 设置',
    switchAutoplaySettings: '打开 No Autoplay 设置',
    switchAnyCopySettings: '打开 Any Copy 设置',
    protectionHeading: '保护功能',
    nativeProtectionHelp: '阻止网页接管滚动操作，保留 Chrome 原生的滚动体验。',
    autoplayProtectionHelp: '阻止网页在未经您操作的情况下播放视频或声音。',
    enhancedSitesHeading: '增强模式网站',
    nativeEnhancedSitesHelp: '仅在符合规则的网站上使用范围更广的滚动保护。',
    autoplayEnhancedSitesHelp: '移除符合规则的网站中的视频和音频元素，之后新增的媒体也会被移除。',
    anyCopyEnhancedSitesHelp: '将符合规则的网页整理为简洁的静态阅读页面，文字可自由选择，图片也不会被遮挡。',
    enforcedSitesHeading: '执行网站',
    enforcedSitesHelp: 'Any Copy 会在符合规则的网站上恢复文字选择，并确保复制内容不被网页篡改。',
    whitelistHeading: '白名单',
    nativeWhitelistHelp: 'Native Scroll 不会在符合规则的网站上运行。',
    autoplayWhitelistHelp: 'No Autoplay 不会在符合规则的网站上运行。',
    audioAllowHeading: '始终允许自动播放声音',
    audioAllowHelp: '允许符合规则的网站自动播放音频元素和 Web Audio；自动播放的视频仍会被拦截。',
    anyCopyActivationHeading: '按网站启用',
    anyCopyActivationHelp: '请在插件控制窗口中为当前网站开启 Any Copy。插件默认保存当前主机名，您也可以在下方添加通配规则。',
    rulePlaceholder: 'example.com 或 *.example.com',
    add: '添加',
    removeRule: '移除 {rule}',
    emptyEnhancedSites: '尚未为任何网站开启增强模式。',
    emptyEnforcedSites: '尚未在任何网站上开启 Any Copy。',
    emptyWhitelist: '尚未添加任何网站。',
    emptyAudioAllow: '尚未允许任何网站自动播放声音。',
    exactRuleHelp: 'example.com 仅匹配该主机名；*.example.com 同时匹配根域名及其所有子域名。',
    invalidRule: '请输入有效的主机名，或使用 *.example.com 这样的通配规则。',
    duplicateRule: '该规则已在列表中。',
    languageHeading: '语言',
    nativeLanguageHelp: '选择 Cosmic Gemini 的界面语言。',
    autoplayLanguageHelp: '选择 Cosmic Gemini 的界面语言。',
    anyCopyLanguageHelp: '选择 Cosmic Gemini 的界面语言。',
    english: 'English',
    chinese: '简体中文',
    helpHeading: '工作方式',
    nativeHelpStandard: '标准保护会拦截网页对滚轮和触控板手势的接管，同时保留普通页面控件和可滚动区域的正常操作。',
    nativeHelpEnhanced: '增强保护还会处理模拟页面移动或反复恢复自定义滚动的网页，并且仅在您指定的网站上启用。',
    nativeHelpIndicator: 'Native Scroll 在当前页面拦截滚动代码后，工具栏图标会随之变化。',
    autoplayHelpStandard: 'No Autoplay 会阻止未经您操作便开始播放的媒体；您主动播放的内容仍可正常使用。',
    autoplayHelpEnhanced: '增强保护会从您指定的网站中移除视频和音频元素。',
    autoplayHelpSound: '网站尝试自动播放声音时，您可以继续拦截、本次允许或永久允许该网站播放声音。',
    anyCopyHelpStandard: 'Any Copy 会恢复文字选择和复制快捷键，并阻止网页替换复制内容或添加推广文字。',
    anyCopyHelpEnhanced: '增强模式会在原网页上方生成静态阅读页面；退出增强模式后，原网页会立即恢复。',
    privacyHeading: '隐私',
    privacyText: 'Cosmic Gemini 完全在本地运行，不会发送网络请求。插件仅保存您的设置和您选择的网站规则；临时声音权限会自动删除。',
    version: '版本 {version}',
    unavailable: 'Cosmic Gemini 暂时无法更新设置。'
  }
};

