const CATALOG = {
  'en-US': {
    appName: 'Cosmic Gemini',
    nativeScrollName: 'Native Scroll',
    noAutoplayName: 'No Autoplay',
    featureOnTitle: '{product} is on · Click to turn off',
    featureOffTitle: '{product} is off · Click to turn on',
    standardSiteTitle: 'Standard on this site · Click for Strong',
    strongSiteTitle: 'Strong on this site · Click for Standard',
    strongCoveredTitle: 'Strong mode is set by {rule} · Manage in Settings',
    strongUnavailableTitle: 'Remove this site from the whitelist before using Strong mode',
    addWhitelistTitle: 'Add this site to the {product} whitelist',
    removeWhitelistTitle: 'Remove this site from the {product} whitelist',
    coveredWhitelistTitle: 'Covered by {rule} · Manage in Settings',
    unsupportedTitle: 'This page is unavailable',
    settingsTitle: 'Open {product} settings',
    popupLabel: 'Cosmic Gemini controls',
    settingsHeading: 'Settings',
    switchNativeSettings: 'Open Native Scroll settings',
    switchAutoplaySettings: 'Open No Autoplay settings',
    protectionHeading: 'Protection',
    nativeProtectionHelp: 'Keep browser scrolling in control across websites.',
    autoplayProtectionHelp: 'Stop video and audio that starts without your action.',
    strongSitesHeading: 'Strong sites',
    nativeStrongSitesHelp: 'Use broader scroll protection only on matching websites.',
    autoplayStrongSitesHelp: 'Remove video and audio elements on matching websites, including media added later.',
    whitelistHeading: 'Whitelist',
    nativeWhitelistHelp: 'Native Scroll stays inactive on matching websites.',
    autoplayWhitelistHelp: 'No Autoplay stays inactive on matching websites.',
    audioAllowHeading: 'Always allow sound',
    audioAllowHelp: 'Allow audio elements and Web Audio to start automatically on matching websites. Autoplaying videos remain blocked.',
    rulePlaceholder: 'example.com or *.example.com',
    add: 'Add',
    removeRule: 'Remove {rule}',
    emptyStrongSites: 'No websites use Strong mode.',
    emptyWhitelist: 'No websites have been added.',
    emptyAudioAllow: 'No websites may autoplay sound.',
    exactRuleHelp: 'example.com matches that hostname only. *.example.com also matches the root domain and all of its subdomains.',
    invalidRule: 'Enter a valid hostname or a wildcard such as *.example.com.',
    duplicateRule: 'That rule is already listed.',
    languageHeading: 'Language',
    nativeLanguageHelp: 'Choose the language used by Native Scroll.',
    autoplayLanguageHelp: 'Choose the language used by No Autoplay.',
    english: 'English',
    chinese: '简体中文',
    helpHeading: 'How it works',
    nativeHelpStandard: 'Standard protection intercepts website code that takes over wheel and trackpad gestures while preserving ordinary page controls and scrollable areas.',
    nativeHelpStrong: 'Strong protection also handles pages that simulate movement or repeatedly restore custom scrolling. It applies only to websites you add to Strong sites.',
    nativeHelpIndicator: 'The toolbar icon changes after Native Scroll suppresses scrolling code on the current page.',
    autoplayHelpStandard: 'No Autoplay stops media that starts without a direct action. Media you intentionally play remains available.',
    autoplayHelpStrong: 'Strong protection removes video and audio elements from websites you add to Strong sites.',
    autoplayHelpSound: 'When a website tries to autoplay sound, you can keep blocking it, allow it temporarily, or always allow sound for that website.',
    privacyHeading: 'Privacy',
    privacyText: 'Cosmic Gemini runs locally and makes no network requests. It stores only your settings and the website rules you choose; temporary sound allowances are deleted automatically.',
    version: 'Version {version}',
    unavailable: 'Unable to update Cosmic Gemini.'
  },
  'zh-CN': {
    appName: 'Cosmic Gemini',
    nativeScrollName: 'Native Scroll',
    noAutoplayName: 'No Autoplay',
    featureOnTitle: '{product} 已开启 · 点击关闭',
    featureOffTitle: '{product} 已关闭 · 点击开启',
    standardSiteTitle: '当前网站使用标准模式 · 点击改为强力模式',
    strongSiteTitle: '当前网站使用强力模式 · 点击改为标准模式',
    strongCoveredTitle: '规则 {rule} 已为当前网站开启强力模式 · 前往设置管理',
    strongUnavailableTitle: '请先将当前网站移出白名单，再开启强力模式',
    addWhitelistTitle: '将当前网站加入 {product} 白名单',
    removeWhitelistTitle: '将当前网站移出 {product} 白名单',
    coveredWhitelistTitle: '当前网站已由规则 {rule} 加入白名单 · 前往设置管理',
    unsupportedTitle: '当前页面不支持此操作',
    settingsTitle: '打开 {product} 设置',
    popupLabel: 'Cosmic Gemini 控制项',
    settingsHeading: '设置',
    switchNativeSettings: '打开 Native Scroll 设置',
    switchAutoplaySettings: '打开 No Autoplay 设置',
    protectionHeading: '保护功能',
    nativeProtectionHelp: '阻止网页接管滚动操作，保留 Chrome 原生的滚动体验。',
    autoplayProtectionHelp: '阻止网页在未经您操作的情况下播放视频或声音。',
    strongSitesHeading: '强力模式网站',
    nativeStrongSitesHelp: '仅在符合规则的网站上使用范围更广的滚动保护。',
    autoplayStrongSitesHelp: '移除符合规则的网站中的视频和音频元素，之后新增的媒体也会被移除。',
    whitelistHeading: '白名单',
    nativeWhitelistHelp: 'Native Scroll 不会在符合规则的网站上运行。',
    autoplayWhitelistHelp: 'No Autoplay 不会在符合规则的网站上运行。',
    audioAllowHeading: '始终允许声音',
    audioAllowHelp: '允许符合规则的网站自动播放音频元素和 Web Audio；自动播放的视频仍会被拦截。',
    rulePlaceholder: 'example.com 或 *.example.com',
    add: '添加',
    removeRule: '移除 {rule}',
    emptyStrongSites: '尚未为任何网站开启强力模式。',
    emptyWhitelist: '尚未添加任何网站。',
    emptyAudioAllow: '尚未允许任何网站自动播放声音。',
    exactRuleHelp: 'example.com 仅匹配该主机名；*.example.com 同时匹配根域名及其所有子域名。',
    invalidRule: '请输入有效的主机名，或使用 *.example.com 这样的通配规则。',
    duplicateRule: '该规则已在列表中。',
    languageHeading: '语言',
    nativeLanguageHelp: '选择 Native Scroll 的界面语言。',
    autoplayLanguageHelp: '选择 No Autoplay 的界面语言。',
    english: 'English',
    chinese: '简体中文',
    helpHeading: '工作方式',
    nativeHelpStandard: '标准保护会拦截网页对滚轮和触控板手势的接管，同时保留普通页面控件和可滚动区域的正常操作。',
    nativeHelpStrong: '强力保护还会处理模拟页面移动或反复恢复自定义滚动的网页，并且仅在您指定的网站上启用。',
    nativeHelpIndicator: 'Native Scroll 在当前页面拦截滚动代码后，工具栏图标会随之变化。',
    autoplayHelpStandard: 'No Autoplay 会阻止未经您操作便开始播放的媒体；您主动播放的内容仍可正常使用。',
    autoplayHelpStrong: '强力保护会从您指定的网站中移除视频和音频元素。',
    autoplayHelpSound: '网站尝试自动播放声音时，您可以继续拦截、本次允许或永久允许该网站播放声音。',
    privacyHeading: '隐私',
    privacyText: 'Cosmic Gemini 完全在本地运行，不会发送网络请求。插件仅保存您的设置和您选择的网站规则；临时声音权限会自动删除。',
    version: '版本 {version}',
    unavailable: 'Cosmic Gemini 暂时无法更新设置。'
  }
};

export function translator(locale) {
  const language = locale === 'zh-CN' ? 'zh-CN' : 'en-US';
  return (key, values = {}) => {
    let value = CATALOG[language][key] ?? CATALOG['en-US'][key] ?? key;
    for (const [name, replacement] of Object.entries(values)) value = value.replaceAll('{' + name + '}', String(replacement));
    return value;
  };
}

export function localizeDocument(t) {
  for (const element of document.querySelectorAll('[data-i18n]')) element.textContent = t(element.dataset.i18n);
  for (const element of document.querySelectorAll('[data-i18n-placeholder]')) element.placeholder = t(element.dataset.i18nPlaceholder);
}
