export const labels = {
  'en-US': {
    theme:'Switch light/dark mode', print:'Print', download:'Download original', sidebar:'Pages and outline', previous:'Previous page', next:'Next page', page:'Page', zoom:'Zoom', zoomOut:'Zoom out', zoomIn:'Zoom in', fitWidth:'Fit width', fitPage:'Fit page', rotate:'Rotate left', fullscreen:'Full screen', exitFullscreen:'Exit full screen', fullScreenFailed:'Full screen is not available in this window.', close:'Close', pages:'Pages', outline:'Outline', password:'Password', cancel:'Cancel', open:'Open', printRange:'Choose pages to print (up to 50 at a time).', from:'From page', to:'To page', loading:'Opening PDF…', failed:'This PDF could not be displayed. You can still download the original.', noOutline:'This document has no outline.', passwordNeeded:'Enter the password to open this PDF.', passwordWrong:'Incorrect password. Please try again.', printing:'Preparing pages for printing…', printFailed:'These pages could not be prepared. Try printing a smaller range.', invalidRange:'Choose a valid range of up to 50 pages.', pageError:'A page could not be rendered. Try changing the zoom or download the original.', cancelled:'Opening cancelled. You can download the original.'
  },
  'zh-CN': {
    theme:'切换浅色／深色模式', print:'打印', download:'下载原文件', sidebar:'页面和目录', previous:'上一页', next:'下一页', page:'页码', zoom:'缩放', zoomOut:'缩小', zoomIn:'放大', fitWidth:'适合宽度', fitPage:'适合页面', rotate:'向左旋转', fullscreen:'全屏', exitFullscreen:'退出全屏', fullScreenFailed:'当前窗口无法进入全屏。', close:'关闭', pages:'页面', outline:'目录', password:'密码', cancel:'取消', open:'打开', printRange:'选择要打印的页面（每次最多 50 页）。', from:'起始页', to:'结束页', loading:'正在打开 PDF…', failed:'无法显示此 PDF，您仍可下载原文件。', noOutline:'此文档没有目录。', passwordNeeded:'请输入密码以打开此 PDF。', passwordWrong:'密码不正确，请重试。', printing:'正在准备打印页面…', printFailed:'无法准备这些页面，请尝试减少打印页数。', invalidRange:'请选择有效的页码范围，每次最多 50 页。', pageError:'有页面未能显示，请尝试调整缩放比例或下载原文件。', cancelled:'已取消打开，您仍可下载原文件。'
  }
};
Object.assign(labels['en-US'], {properties:'Document properties', propertiesLoading:'Reading document properties…', propertiesUnavailable:'Some document properties could not be read.', fileName:'File name', fileSize:'File size', documentTitle:'Title', author:'Author', subject:'Subject', keywords:'Keywords', created:'Created', modified:'Modified', application:'Application', producer:'PDF producer', pdfVersion:'PDF version', pageCount:'Page count', pageSize:'Page size', fastWebView:'Fast web view', yes:'Yes', no:'No'});
Object.assign(labels['zh-CN'], {properties:'文档信息', propertiesLoading:'正在读取文档信息…', propertiesUnavailable:'部分文档信息无法读取。', fileName:'文件名', fileSize:'文件大小', documentTitle:'标题', author:'作者', subject:'主题', keywords:'关键词', created:'创建时间', modified:'修改时间', application:'创建应用', producer:'PDF 生成程序', pdfVersion:'PDF 版本', pageCount:'页数', pageSize:'页面尺寸', fastWebView:'快速 Web 查看', yes:'是', no:'否'});
