globalThis.COSMIC_GEMINI_CATALOG = {
  'en-US': {
    appName: 'Cosmic Gemini',
    nativeScrollName: 'Native Scroll',
    noAutoplayName: 'No Autoplay',
    anyCopyName: 'Any Copy',
    anyCopyEnhancedName: 'Any Copy Enhanced',
    imageDownloadName: 'Image Download',
    videoDownloadName: 'Video Download',
    satellitesName: 'Satellites',
    pageProtectionToolsLabel: 'Page controls',
    enableProductOnSiteTitle: 'Enable {product} on this site',
    disableProductOnSiteTitle: 'Disable {product} on this site',
    removeSiteOverrideTitle: '{product} has a site override · Click to follow the broader setting',
    useEnhancedOnSiteTitle: 'Use {product} Enhanced mode on this site',
    useStandardOnSiteTitle: 'Return {product} to Standard mode on this site',
    featureOnTitle: '{product} is on · Click to turn off',
    featureOffTitle: '{product} is off · Click to turn on',
    standardSiteTitle: 'Standard on this site · Click for Enhanced',
    removeEnhancedRuleTitle: 'Enhanced mode is set by {rule} · Click to remove this rule',
    enhancedUnavailableTitle: 'Remove this site from the whitelist before using Enhanced mode',
    anyCopyOffTitle: 'Enable Any Copy on this site',
    anyCopyOnTitle: 'Any Copy is active on this site · Click to turn off',
    anyCopyCoveredTitle: 'Any Copy is enabled by {rule} · Click to remove the matching rule and turn off',
    anyCopyEnhancedOffTitle: 'Open Any Copy Enhanced in this tab',
    anyCopyEnhancedOnTitle: 'Any Copy Enhanced is active in this tab · Click to close',
    siteFeatureOffTitle: 'Enable {product} on this site',
    siteFeatureOnTitle: '{product} is active on this site · Click to turn off',
    siteFeatureCoveredTitle: '{product} is enabled by {rule} · Click to remove the matching rule and turn off',
    quickToolsLabel: 'Quick tools',
    allSettingsTitle: 'Open All Settings',
    imageStartTitle: 'Find images in this tab',
    imageOpenTitle: 'Open images found in this tab',
    videoStartTitle: 'Find videos in this tab',
    videoOpenTitle: 'Open videos found in this tab',
    videoStopTitle: 'Stop Video Download in this tab',
    videoRescanTitle: 'Scan this tab again',
    addWhitelistTitle: 'Add this site to the {product} whitelist',
    removeWhitelistTitle: 'Remove this site from the {product} whitelist',
    removeCoveredWhitelistTitle: 'Whitelisted by {rule} · Click to remove this rule',
    unsupportedTitle: 'This page is unavailable',
    settingsTitle: 'Open {product} settings',
    popupLabel: 'Cosmic Gemini controls',
    nativeScrollControlsLabel: 'Native Scroll controls',
    noAutoplayControlsLabel: 'No Autoplay controls',
    anyCopyControlsLabel: 'Any Copy controls',
    downloadToolsLabel: 'Download tools',
    settingsHeading: 'Settings',
    switchNativeSettings: 'Open Native Scroll settings',
    switchAutoplaySettings: 'Open No Autoplay settings',
    switchAnyCopySettings: 'Open Any Copy settings',
    switchImageDownloadSettings: 'Open Image Download settings',
    switchVideoDownloadSettings: 'Open Video Download settings',
    switchSatellitesSettings: 'Open Satellites settings',
    switchAllSettings: 'Open All Settings',
    nativeStandardHeading: 'Native Scroll – Standard mode',
    autoplayStandardHeading: 'No Autoplay – Standard mode',
    nativeIntroPurpose: 'Keep browser scrolling in control across websites.',
    autoplayIntroPurpose: 'Stop video and audio that starts without your action.',
    nativeProtectionHelp: 'Enabled by default. Website settings can override this preference.',
    autoplayProtectionHelp: 'Enabled by default. Website settings can override this preference.',
    websiteBehaviorHeading: 'Website settings',
    nativeWebsiteBehaviorHelp: 'Choose how Native Scroll should behave on specific websites.',
    autoplayWebsiteBehaviorHelp: 'Choose how No Autoplay should behave on specific websites.',
    inactiveSitesHeading: 'Always inactive',
    standardSitesHeading: 'Always use Standard mode',
    enhancedSitesHeading: 'Always use Enhanced mode',
    inactiveSitesHelp: 'Keep this feature inactive at all times on matching websites.',
    standardSitesHelp: 'Use Standard mode at all times on matching websites.',
    enhancedSitesHelp: 'Use Enhanced mode at all times on matching websites.',
    sharedWhitelistHeading: 'Shared whitelist',
    sharedWhitelistHelp: 'Keep both Native Scroll and No Autoplay inactive on matching websites. Changes made here appear in both settings pages.',
    emptySharedWhitelist: 'The shared whitelist is empty.',
    nsnaWhitelistActiveTitle: 'Native Scroll and No Autoplay are inactive because this site matches the shared whitelist',
    websiteRuleLabel: 'Website',
    websiteBehaviorLabel: 'Behavior',
    changeBehaviorForRule: 'Change behavior for {rule}',
    anyCopyEnhancedTabHelp: 'Open Any Copy Enhanced from the popup when you want a clean, static reading view in the current tab. It remains limited to that tab and ends when you turn it off or close the tab.',
    enforcedSitesHeading: 'Any Copy sites',
    enforcedSitesHelp: 'Any Copy restores selection and preserves the text you copy on matching websites.',
    anyCopyIntroHelp: 'Restore text selection and copying while keeping clipboard content unchanged on selected websites.',
    anyCopySitesHeading: 'Any Copy sites',
    anyCopySitesHelp: 'Restore text selection, copy shortcuts, and unchanged clipboard content on matching websites.',
    currentTabOnlyLabel: 'On click',
    whitelistHeading: 'Whitelist',
    nativeWhitelistHelp: 'Native Scroll stays inactive on matching websites.',
    autoplayWhitelistHelp: 'No Autoplay stays inactive on matching websites. Video, audio, and Web Audio may autoplay there.',
    audioAllowHeading: 'Audio autoplay',
    audioAllowHelp: 'Keep audio autoplay blocked, allow it everywhere, or allow it only on selected websites. Video autoplay is controlled separately above.',
    audioAllowAllSitesHeading: 'Allow audio autoplay on all sites',
    audioAllowAllSitesHelp: 'Allow audio elements and Web Audio to start automatically on every website. Autoplaying videos remain blocked.',
    audioAllowedSitesHeading: 'Allowed websites',
    audioAllowedSitesHelp: 'Allow audio elements and Web Audio to start automatically only on matching websites.',
    anyCopyStandardHeading: 'Any Copy',
    siteActivationLabel: 'Site activation',
    anyCopyActivationHelp: 'Enable Any Copy for the current website from the extension popup. Exact hostnames are saved by default; wildcard rules can be added below.',
    rulePlaceholder: 'example.com or *.example.com',
    add: 'Add',
    removeRule: 'Remove {rule}',
    emptyInactiveSites: 'No websites are always inactive.',
    emptyStandardSites: 'No websites always use Standard mode.',
    emptyEnhancedSites: 'No websites always use Enhanced mode.',
    emptyEnforcedSites: 'Any Copy is not enabled on any website.',
    emptyAnyCopySites: 'Any Copy is not enabled on any website.',
    emptyAudioAllow: 'No websites may use audio autoplay.',
    exactRuleHelp: 'example.com matches that hostname only. *.example.com also matches the root domain and all of its subdomains.',
    exactHostnameHelp: 'example.com matches that hostname only.',
    wildcardHostnameHelp: '*.example.com also matches the root domain and all of its subdomains.',
    invalidRule: 'Enter a valid hostname or a wildcard such as *.example.com.',
    duplicateRule: 'That rule is already listed.',
    languageHeading: 'Language',
    english: 'English',
    chinese: '简体中文',
    helpHeading: 'How it works',
    setupGuideHeading: 'Recommended setup',
    nativeSetupStepDefault: 'Leave Native Scroll active by default for a consistent scrolling experience.',
    nativeSetupStepExceptions: 'Add only websites that should always remain inactive or use a fixed mode.',
    nativeSetupStepEnhanced: 'Choose Enhanced mode only when Standard mode cannot keep the page from taking scrolling back.',
    autoplaySetupStepDefault: 'Leave No Autoplay active by default to stop media that starts on its own.',
    autoplaySetupStepExceptions: 'Add only websites that should always remain inactive or use a fixed mode.',
    autoplaySetupStepEnhanced: 'Choose Enhanced mode only when removing media elements is the desired result.',
    autoplaySetupStepAudio: 'Allow audio autoplay everywhere or on selected websites only when you want it.',
    nativeHelpStandard: 'Native Scroll intercepts website code that takes over wheel and trackpad gestures in Standard mode while preserving ordinary page controls and scrollable areas.',
    nativeHelpEnhanced: 'Enhanced mode also handles pages that simulate movement or repeatedly restore custom scrolling. Use it only for websites set to Always use Enhanced mode.',
    nativeHelpIndicator: 'The toolbar icon changes after Native Scroll suppresses scrolling code on the current page.',
    autoplayHelpStandard: 'No Autoplay stops media that starts without a direct action. Media you intentionally play remains available.',
    autoplayHelpEnhanced: 'Enhanced mode removes video and audio elements from websites set to Always use Enhanced mode.',
    autoplayHelpSound: 'Audio autoplay remains blocked unless you allow it for all sites or through a matching website rule. These audio permissions do not allow autoplaying video.',
    anyCopyHelpStandard: 'Any Copy restores text selection, keeps copy shortcuts available, and prevents websites from replacing copied content or adding promotional text.',
    anyCopyHelpEnhanced: 'Open Any Copy Enhanced for the current tab to place a static reading view over the original page. Turning it off restores the original page immediately without changing Any Copy.',
    imageDownloadActivationHelp: 'Open the extension popup and click Image Download to find images in the current tab. The workspace opens beside the page by default.',
    imageDownloadPreferencesHeading: 'Download preferences',
    imageDownloadPreferencesHelp: 'Choose where the workspace opens, along with its default format and batch-download behavior.',
    imageWorkspaceModeHeading: 'Workspace location',
    imageWorkspaceModeHelp: 'Keep the source page visible with the Side Panel, or use a separate tab.',
    imageWorkspaceSidePanel: 'Side panel',
    imageWorkspacePage: 'Separate tab',
    imageOutputFormatHeading: 'Default image format',
    imageOutputFormatHelp: 'Keep each original format or convert compatible images locally before downloading.',
    imageBatchModeHeading: 'Multiple-image downloads',
    imageBatchModeHelp: 'Place selected images in one ZIP file or send them to Chrome as separate files.',
    keepOriginalFormat: 'Keep original format',
    downloadAsZip: 'Download as ZIP',
    downloadSeparately: 'Download separately',
    imageDownloadHelpDetection: 'Image Download finds responsive images, lazy-loaded sources, linked originals, CSS images, frames, open shadow roots, inline SVG, canvas content, structured metadata, and image requests observed during the active session.',
    imageDownloadHelpOriginals: 'Related thumbnails and alternate formats are grouped together. The highest-quality verified candidate is recommended while other available sizes remain selectable.',
    imageDownloadHelpBatch: 'The workspace provides previews, filters, sorting, selection, local format conversion, separate downloads, and local ZIP creation.',
    imageDownloadPrivacy: 'Image Download keeps page and image information only for the active tab session and does not save browsing or download history. Selected images are fetched from their source and processed locally.',
    videoDownloadActivationHelp: 'Open the extension popup and click Video Download to find downloadable media in the current tab.',
    clickToEnableLabel: 'On click',
    videoDownloadPreferencesHeading: 'Download preferences',
    videoDownloadPreferencesHelp: 'Choose how Video Download selects streams and starts Chrome downloads.',
    preferredQualityHeading: 'Preferred quality',
    preferredQualityHelp: 'The closest available quality is used when a stream offers several variants.',
    qualityBest: 'Best available',
    askWhereToSaveHeading: 'Ask where to save',
    askWhereToSaveHelp: 'Show Chrome’s save dialog before each file is downloaded.',
    videoDownloadHelpDetection: 'Video Download combines network requests, player state, streaming manifests, embedded frames, and dedicated support for compatible video services.',
    videoDownloadHelpFormats: 'Direct files, compatible HLS and DASH streams, separate video and audio tracks, subtitles, and live snapshots are processed locally. Standard AES-128 HLS and supported wrapped HLS playlists are also handled.',
    videoDownloadHelpSession: 'Detection applies only to the current tab. It continues through same-site navigation and ends when the tab changes to another website, closes, or you stop it.',
    videoDownloadPrivacy: 'Video Download keeps detected media information only for the active tab session and does not save browsing or download history. Selected media is fetched from its source and processed locally.',
    back: 'Back',
    download: 'Download',
    videoScanningHelp: 'Looking for video. If nothing appears, play the video once and reopen this panel.',
    videoUnavailablePage: 'Video Download cannot inspect this page.',
    videoStopped: 'Video Download has stopped in this tab.',
    videoFound: 'Download options: {count}',
    videoMediaFound: 'Videos found: {count}',
    videoItem: 'Video {index}',
    videoQuality: 'Quality',
    videoGroup: 'Video',
    audioGroup: 'Audio',
    subtitleGroup: 'Subtitles',
    videoAudioOnly: 'Audio only',
    videoAudioFile: 'Audio file',
    otherFormats: 'Other formats ({count})',
    videoStream: 'HLS stream',
    videoCombinedStream: 'Video + audio',
    videoDashStream: 'DASH stream',
    videoSubtitles: 'Subtitles',
    videoProtectedMedia: 'Protected media',
    videoFile: 'Video file',
    videoLiveSnapshot: 'Current live segment window',
    videoUnavailableFormat: 'Unavailable',
    videoPreparing: 'Preparing {progress}%',
    videoCancelProcessingTitle: 'Cancel processing',
    videoDownloading: 'Downloading',
    videoDownloaded: 'Downloaded',
    videoRetry: 'Retry',
    videoDownloadFailedHelp: 'The selected video could not be downloaded.',
    imageWorkspaceActions: 'Image Download actions',
    imageSearchLabel: 'Search images',
    imageFiltersHeading: 'Filters',
    activeFilterCount: '{count} active filters',
    imageSearchPlaceholder: 'Search filename, description, or address',
    imageTypeLabel: 'Type',
    allTypes: 'All types',
    imageLayoutLabel: 'Layout',
    allLayouts: 'All layouts',
    layoutWide: 'Wide',
    layoutTall: 'Tall',
    layoutSquare: 'Square',
    minimumWidth: 'Min width',
    minimumHeight: 'Min height',
    sortBy: 'Sort',
    sortLargest: 'Largest first',
    sortSmallest: 'Smallest first',
    sortPageOrder: 'Page order',
    clearFilters: 'Clear filters',
    selectVisible: 'Select visible',
    clearSelection: 'Clear selection',
    imageOutputFormat: 'Image output format',
    imageBatchMode: 'Image batch mode',
    downloadSelected: 'Download selected',
    downloadSelectedCount: 'Download selected ({count})',
    imageNoResults: 'No matching images',
    imageNoResultsHelp: 'Try clearing the filters or use Full-page scan to load images that appear later on the page.',
    imageFocusSourceTitle: 'Return to the source page',
    imageOpenPageTitle: 'Open in a separate tab',
    imageCaptureAreaTitle: 'Capture an area of the visible page',
    imageRescanTitle: 'Scan the current page again',
    imageDeepScanTitle: 'Scan the full page, including lazy-loaded images',
    imageStopTitle: 'Stop Image Download in this tab',
    imageSessionStarting: 'Starting Image Download…',
    imageFindingImages: 'Finding images…',
    imageCheckingSources: 'Found {count} images · checking available sources…',
    imageScanning: 'Scanning the current page…',
    imageDeepScanning: 'Loading and scanning the full page…',
    imageScanTimedOut: 'The page took too long to scan. Try scanning again.',
    imageUnavailablePage: 'Image Download cannot inspect this page.',
    imageSessionStopped: 'Image Download has stopped in the source tab.',
    imageOriginalPreferred: 'The best available source is recommended for each image.',
    imageResults: 'Images shown: {count}',
    imageNumber: 'Image {number}',
    selectImage: 'Select {name}',
    recommendedOriginal: 'Recommended',
    imageVariantLabel: 'Available sizes and formats',
    alternateImage: 'Alternate image',
    downloadImageTitle: 'Download this image',
    imageDownloadStarted: 'Started downloading {count} image(s).',
    imageDownloadFailed: 'The selected images could not be downloaded.',
    unknownFormat: 'Image',
    biliDailyLoginName: 'Bili Daily Login',
    adMarshalName: 'Ad Marshal',
    adMarshalDescription: 'Some sites repeatedly recreate advertising and tracking requests after a blocker rejects them. When enabled, Ad Marshal applies a dedicated local rule set to its managed sites, stopping matching requests at their source and hiding known advertising components.',
    adMarshalManagedSites: 'Managed sites: news.qq.com (including www.qq.com), douyin.com, and zhihu.com.',
    adMarshalPrivacy: 'Ad Marshal runs locally only on the managed sites listed above. It stores only whether Ad Marshal is enabled and does not record browsing activity.',
    satellitesHelpHeading: 'About Satellites',
    satellitesHelpIntro: 'Satellites is a collection of small, optional tools that handle useful background tasks without adding controls to the popup. Each Satellite can be enabled independently, with its purpose and data use explained in its own card.',
    satellitesOverviewHelp: 'Choose the small background tools you want Cosmic Gemini to handle for you.',
    disabledInIncognito: 'Disabled in Incognito',
    disabledByDefaultInIncognito: 'Disabled by default in Incognito.',
    biliDailyLoginDescription: 'Bilibili gives every signed-in account one coin when it visits each day. Bili Daily Login schedules that visit for 00:05 China Standard Time. If Chrome or the computer is not running then, one current-day task catches up the next time Chrome can run; missed days are never replayed.',
    biliDailyLoginPrivacyHeading: 'Privacy',
    biliDailyLoginPrivacy: 'This feature does not inspect whether or when you open Bilibili. Its background schedule contacts Bilibili only while Chrome and the computer are running and Chrome does not report offline, uses the account already signed in to Chrome, never reads or stores your password, and permanently stores only its switch state and last completed date.',
    privacyHeading: 'Privacy',
    nativePrivacy: 'Native Scroll runs locally. It stores only its switch state and the website rules you choose, and does not send browsing data.',
    autoplayPrivacy: 'No Autoplay runs locally. It stores only its switch state, the audio autoplay setting, and the website rules you choose.',
    anyCopyPrivacy: 'Any Copy and Any Copy Enhanced run locally and never send copied text or browsing data. Any Copy stores only the website rules you choose. Any Copy Enhanced keeps its current-tab state only for that browser session.',
    allSettingsName: 'All Settings',
    allSettingsIntro: 'Open every Cosmic Gemini product setting from one place.',
    allSettingsHelpHeading: 'Settings collection',
    allSettingsHelp: 'Choose a product to open its dedicated settings. Each product keeps its controls and website rules in its own section.',
    allSettingsNativeDescription: 'Configure scrolling protection and website rules.',
    allSettingsAutoplayDescription: 'Configure media blocking and audio autoplay permissions.',
    allSettingsAnyCopyDescription: 'Manage Any Copy websites and learn how Any Copy Enhanced works in the current tab.',
    allSettingsImageDescription: 'Choose the image workspace and download defaults.',
    allSettingsVideoDescription: 'Choose preferred video quality and download behavior.',
    allSettingsSatellitesDescription: 'Manage optional background tools.',
    resetAllSettingsHeading: 'Reset settings',
    resetAllSettingsHelp: 'Restore every product setting and website rule to its default.',
    resetAllSettingsAction: 'Reset all settings',
    resetAllSettingsConfirmHeading: 'Reset all settings?',
    resetAllSettingsConfirmHelp: 'This restores every setting, removes saved website rules, and stops current temporary sessions. Files already downloaded are unaffected.',
    cancel: 'Cancel',
    reset: 'Reset',
    version: 'Version {version}',
    unavailable: 'Unable to update Cosmic Gemini.'
  },
  'zh-CN': {
    appName: 'Cosmic Gemini',
    nativeScrollName: 'Native Scroll',
    noAutoplayName: 'No Autoplay',
    anyCopyName: 'Any Copy',
    anyCopyEnhancedName: 'Any Copy 强力模式',
    imageDownloadName: 'Image Download',
    videoDownloadName: 'Video Download',
    satellitesName: 'Satellites',
    pageProtectionToolsLabel: '页面功能',
    enableProductOnSiteTitle: '在此网站启用 {product}',
    disableProductOnSiteTitle: '在此网站停用 {product}',
    removeSiteOverrideTitle: '{product} 已单独设置，点击后改为遵循上级设置',
    useEnhancedOnSiteTitle: '在此网站使用 {product} 强力模式',
    useStandardOnSiteTitle: '在此网站恢复使用 {product} 标准模式',
    featureOnTitle: '{product} 已开启 · 点击关闭',
    featureOffTitle: '{product} 已关闭 · 点击开启',
    standardSiteTitle: '当前网站使用标准模式 · 点击改为强力模式',
    removeEnhancedRuleTitle: '规则 {rule} 已为当前网站开启强力模式 · 点击移除该规则',
    enhancedUnavailableTitle: '请先将当前网站移出白名单，再开启强力模式',
    anyCopyOffTitle: '在当前网站开启 Any Copy',
    anyCopyOnTitle: 'Any Copy 正在当前网站运行 · 点击关闭',
    anyCopyCoveredTitle: '规则 {rule} 已为当前网站开启 Any Copy · 点击移除该规则并关闭',
    anyCopyEnhancedOffTitle: '在当前标签页中打开 Any Copy 强力模式',
    anyCopyEnhancedOnTitle: 'Any Copy 强力模式正在当前标签页中运行 · 点击关闭',
    siteFeatureOffTitle: '在当前网站开启 {product}',
    siteFeatureOnTitle: '{product} 正在当前网站运行 · 点击关闭',
    siteFeatureCoveredTitle: '规则 {rule} 已为当前网站开启 {product} · 点击移除该规则并关闭',
    quickToolsLabel: '快捷工具',
    allSettingsTitle: '打开全部设置',
    imageStartTitle: '查找当前标签页中的图片',
    imageOpenTitle: '打开当前标签页的图片工作区',
    videoStartTitle: '查找当前标签页中的视频',
    videoOpenTitle: '查看当前标签页中找到的视频',
    videoStopTitle: '停止在当前标签页中查找视频',
    videoRescanTitle: '重新扫描当前标签页',
    addWhitelistTitle: '将当前网站加入 {product} 白名单',
    removeWhitelistTitle: '将当前网站移出 {product} 白名单',
    removeCoveredWhitelistTitle: '规则 {rule} 已将当前网站加入白名单 · 点击移除该规则',
    unsupportedTitle: '当前页面不支持此操作',
    settingsTitle: '打开 {product} 设置',
    popupLabel: 'Cosmic Gemini 控制项',
    nativeScrollControlsLabel: 'Native Scroll 控制项',
    noAutoplayControlsLabel: 'No Autoplay 控制项',
    anyCopyControlsLabel: 'Any Copy 控制项',
    downloadToolsLabel: '下载工具',
    settingsHeading: '设置',
    switchNativeSettings: '打开 Native Scroll 设置',
    switchAutoplaySettings: '打开 No Autoplay 设置',
    switchAnyCopySettings: '打开 Any Copy 设置',
    switchImageDownloadSettings: '打开 Image Download 设置',
    switchVideoDownloadSettings: '打开 Video Download 设置',
    switchSatellitesSettings: '打开 Satellites 设置',
    switchAllSettings: '打开全部设置',
    nativeStandardHeading: 'Native Scroll – 标准模式',
    autoplayStandardHeading: 'No Autoplay – 标准模式',
    nativeIntroPurpose: '阻止网页接管滚动操作，保留 Chrome 原生的滚动体验。',
    autoplayIntroPurpose: '阻止网页在未经您操作的情况下播放视频或声音。',
    nativeProtectionHelp: '默认启用，您可以在下方为指定网站设置不同的运行方式。',
    autoplayProtectionHelp: '默认启用，您可以在下方为指定网站设置不同的运行方式。',
    websiteBehaviorHeading: '网站设置',
    nativeWebsiteBehaviorHelp: '为指定网站选择 Native Scroll 的固定运行方式。',
    autoplayWebsiteBehaviorHelp: '为指定网站选择 No Autoplay 的固定运行方式。',
    inactiveSitesHeading: '始终停用',
    standardSitesHeading: '始终使用标准模式',
    enhancedSitesHeading: '始终使用强力模式',
    inactiveSitesHelp: '符合规则的网站始终停用此功能。',
    standardSitesHelp: '符合规则的网站始终使用标准模式。',
    enhancedSitesHelp: '符合规则的网站始终使用强力模式。',
    sharedWhitelistHeading: '共用白名单',
    sharedWhitelistHelp: '白名单中的网站不会启用 Native Scroll 和 No Autoplay。这里的修改会同步显示在两个设置页面中。',
    emptySharedWhitelist: '共用白名单中尚无网站。',
    nsnaWhitelistActiveTitle: '当前网站在共用白名单中，Native Scroll 和 No Autoplay 均已停用',
    websiteRuleLabel: '网站',
    websiteBehaviorLabel: '运行方式',
    changeBehaviorForRule: '更改 {rule} 的运行方式',
    anyCopyEnhancedTabHelp: '需要简洁的静态阅读页面时，请从控制窗口为当前标签页打开 Any Copy 强力模式。该模式只在此标签页中运行，手动关闭或关闭标签页后即会结束。',
    enforcedSitesHeading: 'Any Copy 网站',
    enforcedSitesHelp: 'Any Copy 会在符合规则的网站上恢复文字选择，并确保复制内容不被网页篡改。',
    anyCopyIntroHelp: '恢复指定网站上的文字选择和复制操作，并确保剪贴板内容不被网页篡改。',
    anyCopySitesHeading: 'Any Copy 网站',
    anyCopySitesHelp: '在符合规则的网站上恢复文字选择、复制快捷键和原始剪贴板内容。',
    currentTabOnlyLabel: '点击时',
    whitelistHeading: '白名单',
    nativeWhitelistHelp: 'Native Scroll 不会在符合规则的网站上运行。',
    autoplayWhitelistHelp: 'No Autoplay 不会在符合规则的网站上运行。此类网站可以自动播放视频、声音和 Web Audio。',
    audioAllowHeading: '声音自动播放',
    audioAllowHelp: '声音默认会被拦截。您可以允许所有网站，或仅允许指定网站自动播放声音。视频自动播放仍由上方设置控制。',
    audioAllowAllSitesHeading: '允许所有网站自动播放声音',
    audioAllowAllSitesHelp: '允许所有网站自动播放音频元素和 Web Audio。自动播放的视频仍会被拦截。',
    audioAllowedSitesHeading: '允许的网站',
    audioAllowedSitesHelp: '仅允许符合规则的网站自动播放音频元素和 Web Audio。',
    anyCopyStandardHeading: 'Any Copy',
    siteActivationLabel: '按网站启用',
    anyCopyActivationHelp: '请在插件控制窗口中为当前网站开启 Any Copy。插件默认保存当前主机名，您也可以在下方添加通配规则。',
    rulePlaceholder: 'example.com 或 *.example.com',
    add: '添加',
    removeRule: '移除 {rule}',
    emptyInactiveSites: '尚未设置始终停用的网站。',
    emptyStandardSites: '尚未设置始终使用标准模式的网站。',
    emptyEnhancedSites: '尚未设置始终使用强力模式的网站。',
    emptyEnforcedSites: '尚未在任何网站上开启 Any Copy。',
    emptyAnyCopySites: '尚未在任何网站上开启 Any Copy。',
    emptyAudioAllow: '尚未允许任何网站自动播放声音。',
    exactRuleHelp: 'example.com 仅匹配该主机名。*.example.com 同时匹配根域名及其所有子域名。',
    exactHostnameHelp: 'example.com 仅匹配该主机名。',
    wildcardHostnameHelp: '*.example.com 同时匹配根域名及其所有子域名。',
    invalidRule: '请输入有效的主机名，或使用 *.example.com 这样的通配规则。',
    duplicateRule: '该规则已在列表中。',
    languageHeading: '语言',
    english: 'English',
    chinese: '简体中文',
    helpHeading: '工作方式',
    setupGuideHeading: '建议设置顺序',
    nativeSetupStepDefault: '建议保持 Native Scroll 默认启用，让日常滚动体验更加一致。',
    nativeSetupStepExceptions: '仅添加需要始终停用或固定使用某种模式的网站。',
    nativeSetupStepEnhanced: '只有标准模式无法阻止网页重新接管滚动时，才选择始终使用强力模式。',
    autoplaySetupStepDefault: '建议保持 No Autoplay 默认启用，拦截网页擅自播放的媒体。',
    autoplaySetupStepExceptions: '仅添加需要始终停用或固定使用某种模式的网站。',
    autoplaySetupStepEnhanced: '只有确实需要移除媒体元素时，才选择始终使用强力模式。',
    autoplaySetupStepAudio: '仅在需要时允许所有网站或指定网站自动播放声音。',
    nativeHelpStandard: 'Native Scroll 在标准模式下会拦截网页对滚轮和触控板手势的接管，同时保留普通页面控件和可滚动区域的正常操作。',
    nativeHelpEnhanced: '强力模式还会处理模拟页面移动或反复恢复自定义滚动的网页。请仅为确有需要的网站选择“始终使用强力模式”。',
    nativeHelpIndicator: 'Native Scroll 在当前页面拦截滚动代码后，工具栏图标会随之变化。',
    autoplayHelpStandard: 'No Autoplay 会阻止未经您操作便开始播放的媒体。您主动播放的内容仍可正常使用。',
    autoplayHelpEnhanced: '强力模式会从选择“始终使用强力模式”的网站中移除视频和音频元素。',
    autoplayHelpSound: '除非您允许所有网站或符合规则的网站自动播放声音，否则 No Autoplay 会继续拦截。声音播放权限不会放行自动播放的视频。',
    anyCopyHelpStandard: 'Any Copy 会恢复文字选择和复制快捷键，并阻止网页替换复制内容或添加推广文字。',
    anyCopyHelpEnhanced: '为当前标签页打开 Any Copy 强力模式后，插件会在原网页上方生成静态阅读页面。关闭后会立即恢复原网页，不会改变 Any Copy 的启用状态。',
    imageDownloadActivationHelp: '请打开插件控制窗口，点击 Image Download 查找当前标签页中的图片。图片工作区默认会在网页旁的侧边栏中打开。',
    imageDownloadPreferencesHeading: '下载设置',
    imageDownloadPreferencesHelp: '设置图片工作区的打开位置、默认图片格式和批量下载方式。',
    imageWorkspaceModeHeading: '打开位置',
    imageWorkspaceModeHelp: '使用侧边栏可以保留原网页，也可以选择在独立标签页中打开。',
    imageWorkspaceSidePanel: '侧边栏',
    imageWorkspacePage: '独立标签页',
    imageOutputFormatHeading: '默认图片格式',
    imageOutputFormatHelp: '保留图片原格式，或在下载前于本地转换兼容的图片。',
    imageBatchModeHeading: '多图下载方式',
    imageBatchModeHelp: '将选中的图片放入一个 ZIP 文件，或分别交给 Chrome 下载。',
    keepOriginalFormat: '保留原格式',
    downloadAsZip: '下载为 ZIP',
    downloadSeparately: '分别下载',
    imageDownloadHelpDetection: 'Image Download 会查找响应式图片、懒加载来源、原图链接、CSS 图片、嵌入式页面、开放的 Shadow DOM、内联 SVG、Canvas 内容和结构化数据，也会识别当前会话中出现的图片请求。',
    imageDownloadHelpOriginals: '插件会将同一图片的缩略图、不同尺寸和其他格式归在一起，默认推荐经过识别的最高质量版本，同时保留其他可选版本。',
    imageDownloadHelpBatch: '图片工作区提供预览、筛选、排序、批量选择、本地格式转换、分别下载和本地 ZIP 打包。',
    imageDownloadPrivacy: 'Image Download 只会在当前标签页的临时会话中保留页面与图片信息，不会保存浏览记录或下载历史。选中的图片会从原网站获取，并在本地完成处理。',
    videoDownloadActivationHelp: '请打开插件控制窗口，点击 Video Download 查找当前标签页中可以下载的视频。',
    clickToEnableLabel: '点击时',
    videoDownloadPreferencesHeading: '下载设置',
    videoDownloadPreferencesHelp: '设置 Video Download 选择视频流和开始下载时使用的方式。',
    preferredQualityHeading: '首选画质',
    preferredQualityHelp: '视频流提供多种画质时，插件会选择最接近该设置的一项。',
    qualityBest: '最高可用画质',
    askWhereToSaveHeading: '下载前选择保存位置',
    askWhereToSaveHelp: '每次下载前显示 Chrome 的文件保存窗口。',
    videoDownloadHelpDetection: 'Video Download 会综合分析网络请求、播放器状态、视频流清单和嵌入式页面，并针对兼容的视频服务进行识别。',
    videoDownloadHelpFormats: '插件会在本地处理视频文件、兼容的 HLS 与 DASH 视频流、分离的音视频轨道、字幕和直播片段，也支持标准 AES-128 HLS 与部分经过封装的 HLS 清单。',
    videoDownloadHelpSession: '视频查找仅在当前标签页中启用。站内跳转不会中断，前往其他网站、关闭标签页或手动停止后会自动结束。',
    videoDownloadPrivacy: 'Video Download 只会在当前标签页的临时会话中保留检测到的媒体信息，不会保存浏览记录或下载历史。选中的媒体会从原网站获取，并在本地完成处理。',
    back: '返回',
    download: '下载',
    videoScanningHelp: '正在查找视频。如果没有出现结果，请播放一次视频后重新打开此页面。',
    videoUnavailablePage: 'Video Download 无法检查当前页面。',
    videoStopped: '已停止在当前标签页中查找视频。',
    videoFound: '可下载选项：{count}',
    videoMediaFound: '发现 {count} 个视频',
    videoItem: '视频 {index}',
    videoQuality: '清晰度',
    videoGroup: '视频',
    audioGroup: '音频',
    subtitleGroup: '字幕',
    videoAudioOnly: '仅音频',
    videoAudioFile: '音频文件',
    otherFormats: '其他格式（{count}）',
    videoStream: 'HLS 视频流',
    videoCombinedStream: '视频与音频',
    videoDashStream: 'DASH 视频流',
    videoSubtitles: '字幕',
    videoProtectedMedia: '受保护媒体',
    videoFile: '视频文件',
    videoLiveSnapshot: '当前直播片段',
    videoUnavailableFormat: '暂不支持',
    videoPreparing: '正在处理 {progress}%',
    videoCancelProcessingTitle: '取消处理',
    videoDownloading: '正在下载',
    videoDownloaded: '下载完成',
    videoRetry: '重试',
    videoDownloadFailedHelp: '无法下载所选视频。',
    imageWorkspaceActions: 'Image Download 操作',
    imageSearchLabel: '搜索图片',
    imageFiltersHeading: '筛选',
    activeFilterCount: '已启用 {count} 项筛选条件',
    imageSearchPlaceholder: '搜索文件名、说明或地址',
    imageTypeLabel: '格式',
    allTypes: '全部格式',
    imageLayoutLabel: '方向',
    allLayouts: '全部方向',
    layoutWide: '横向',
    layoutTall: '纵向',
    layoutSquare: '方形',
    minimumWidth: '最小宽度',
    minimumHeight: '最小高度',
    sortBy: '排序',
    sortLargest: '尺寸从大到小',
    sortSmallest: '尺寸从小到大',
    sortPageOrder: '网页顺序',
    clearFilters: '清除筛选',
    selectVisible: '选择当前结果',
    clearSelection: '清除选择',
    imageOutputFormat: '图片输出格式',
    imageBatchMode: '图片批量下载方式',
    downloadSelected: '下载所选图片',
    downloadSelectedCount: '下载所选图片（{count}）',
    imageNoResults: '没有符合条件的图片',
    imageNoResultsHelp: '您可以清除筛选条件，或使用完整扫描加载网页后续出现的图片。',
    imageFocusSourceTitle: '返回原网页',
    imageOpenPageTitle: '在独立标签页中打开',
    imageCaptureAreaTitle: '截取当前可见网页中的区域',
    imageRescanTitle: '重新扫描当前页面',
    imageDeepScanTitle: '完整扫描网页并加载懒加载图片',
    imageStopTitle: '停止在当前标签页中查找图片',
    imageSessionStarting: '正在启动 Image Download…',
    imageFindingImages: '正在查找图片…',
    imageCheckingSources: '已找到 {count} 张图片，正在检查可用来源…',
    imageScanning: '正在扫描当前页面…',
    imageDeepScanning: '正在加载并扫描完整网页…',
    imageScanTimedOut: '扫描网页所需时间过长，请重新扫描。',
    imageUnavailablePage: 'Image Download 无法检查当前页面。',
    imageSessionStopped: '原标签页中的 Image Download 已停止。',
    imageOriginalPreferred: '每组图片均会优先推荐质量最高的可用来源。',
    imageResults: '当前显示 {count} 张图片',
    imageNumber: '图片 {number}',
    selectImage: '选择{name}',
    recommendedOriginal: '推荐版本',
    imageVariantLabel: '可用尺寸与格式',
    alternateImage: '其他版本',
    downloadImageTitle: '下载该图片',
    imageDownloadStarted: '已开始下载 {count} 张图片。',
    imageDownloadFailed: '无法下载所选图片。',
    unknownFormat: '图片',
    biliDailyLoginName: 'Bili Daily Login',
    adMarshalName: 'Ad Marshal',
    adMarshalDescription: '部分网站会在广告或跟踪请求被拦截后不断重新创建相同请求。开启后，Ad Marshal 会在管制网站中应用专用规则，从源头停止符合条件的请求，并隐藏已知的广告组件。',
    adMarshalManagedSites: '管制网站：news.qq.com（包括 www.qq.com）、douyin.com 和 zhihu.com。',
    adMarshalPrivacy: 'Ad Marshal 仅在上方所列的管制网站中本地运行，只保存功能是否开启，不记录浏览活动。',
    satellitesHelpHeading: '关于 Satellites',
    satellitesHelpIntro: 'Satellites 汇集了一些无需占用控制窗口的小功能，用于完成实用的后台任务。各项功能可单独开启，相关用途和数据处理方式会在对应的设置卡片中说明。',
    satellitesOverviewHelp: '您可以在这里选择需要 Cosmic Gemini 在后台完成的小功能。',
    disabledInIncognito: '已在无痕模式下停用',
    disabledByDefaultInIncognito: '在无痕模式下默认停用。',
    biliDailyLoginDescription: '哔哩哔哩每天会向访问网站的登录账号发放一枚硬币。Bili Daily Login 按北京时间每天 00:05 安排访问。若当时 Chrome 未运行或电脑处于休眠状态，则在 Chrome 下次可以运行时仅补做当天任务，不追补此前错过的日期。',
    biliDailyLoginPrivacyHeading: '隐私',
    biliDailyLoginPrivacy: '本功能不会判断或记录您是否、何时打开哔哩哔哩。后台日程仅在电脑已唤醒、Chrome 正在运行且未报告离线时访问哔哩哔哩服务，直接使用 Chrome 中已有的登录状态，不读取或保存密码。长期保存的内容仅包括功能开关和最近一次完成日期。',
    privacyHeading: '隐私',
    nativePrivacy: 'Native Scroll 完全在本地运行，仅保存功能开关和您选择的网站规则，不会发送浏览数据。',
    autoplayPrivacy: 'No Autoplay 完全在本地运行，仅保存功能开关、声音自动播放设置和您选择的网站规则。',
    anyCopyPrivacy: 'Any Copy 与 Any Copy 强力模式完全在本地运行，不会发送复制内容或浏览数据。Any Copy 仅保存您选择的网站规则，强力模式的当前标签页状态只在本次浏览器会话中保留。',
    allSettingsName: '全部设置',
    allSettingsIntro: '在一个页面中进入 Cosmic Gemini 各项功能的设置。',
    allSettingsHelpHeading: '设置导航',
    allSettingsHelp: '请选择需要设置的功能。每项功能都会在自己的页面中管理操作选项和网站规则。',
    allSettingsNativeDescription: '设置滚动保护和网站规则。',
    allSettingsAutoplayDescription: '设置媒体拦截和声音自动播放权限。',
    allSettingsAnyCopyDescription: '管理 Any Copy 网站，并了解 Any Copy 强力模式在当前标签页中的使用方式。',
    allSettingsImageDescription: '设置图片工作区和默认下载方式。',
    allSettingsVideoDescription: '设置视频画质和下载方式。',
    allSettingsSatellitesDescription: '管理可选的后台小功能。',
    resetAllSettingsHeading: '重置设置',
    resetAllSettingsHelp: '将各项功能设置和网站规则恢复为默认状态。',
    resetAllSettingsAction: '重置所有设置',
    resetAllSettingsConfirmHeading: '重置所有设置？',
    resetAllSettingsConfirmHelp: '此操作会恢复全部默认设置、移除已保存的网站规则，并结束当前的临时任务。已下载的文件不受影响。',
    cancel: '取消',
    reset: '重置',
    version: '版本 {version}',
    unavailable: 'Cosmic Gemini 暂时无法更新设置。'
  }
};
