globalThis.COSMIC_GEMINI_CATALOG = {
  'en-US': {
    documentPreviewName: "Document Preview",
    documentPreviewDescription: "Preview .docx documents directly in your browser, without saving them first. Switch between light and dark views while reading, and download the original file whenever you need it.",
    documentPreviewPrivacy: "Documents are processed on your device and are not uploaded to another service. Temporary files and choices are cleared when the website’s last open tab closes or leaves. A cached file is also cleared 10 hours after its last preview closes, whichever happens first.",
    documentPreviewAction: "Preview",
    documentZoom: "Document zoom",
    documentZoomOut: "Zoom out by 10%",
    documentZoomIn: "Zoom in by 10%",
    documentZoomReset: "Reset zoom to 100%",
    documentDownloadAction: "Download",
    documentClose: "Close",
    documentRemember: "Use the selected action for this website this time.",
    documentActionFailed: "Could not complete this action. Please try again.",
    documentLoading: "Preparing the document…",
    documentLayoutNote: "Content preview — complex formatting may differ from Word.",
    documentExpired: "This preview has expired. Open the source website and select the document again.",
    documentRenderFailed: "This document could not be displayed. You can still download the original file.",
    documentDownloadStarted: "The file has been sent to Chrome for downloading.",
    documentResetChoice: "Document Preview: {action}. Click to ask each time again.",
    documentAutoPreview: "Preview for this website",
    documentAutoDownload: "Download for this website",
    documentAppearance: "Appearance",
    documentAppearanceHelp: "Choose the default preview appearance. Changes made in a preview apply to this website until its last tab closes or leaves.",
    documentAppearanceAuto: "Auto",
    documentAppearanceLight: "Light",
    documentAppearanceDark: "Dark",
    documentThemeAuto: "Default",
    documentThemeFollow: "Use the appearance selected in Settings",
    documentThemeLight: "Switch to light mode",
    documentThemeDark: "Switch to dark mode",
    langGoogleName: "Serch Result Language Designate for Google Search",
    langGoogleDescription: "Specify Google Search result languages using “lang:” in the search box. Combine multiple languages across web, video, image, and other search categories.",
    langGooglePrivacy: "Search URL processing stays on your device. No search history is stored or sent to any additional service.",
    igCloseDialog: "Close the open Instagram dialog, then check again.",
    igListChanged: "The list search changed during reading. Clear it and check again.",
    followListInstagramName: "Following/Follower List Check for Instagram",
    followListInstagramDescription: "Compare an Instagram profile’s following and follower lists in a side panel. See who has not followed back, mutual follows, and followers the profile does not follow. On your own profile, the tool can open Instagram’s confirmation for an account that has not followed you back, where you choose whether to unfollow.",
    followListInstagramHelp: "Open an Instagram profile, then click the IG± button in the extension popup to start. Reading continues if you close the side panel. Reopen it to see the progress or results; choose Stop to end the check.",
    followListInstagramPrivacy: "Lists displayed by Instagram are read in your current tab and compared locally. Complete results remain only for the current browser session and are cleared when the browser exits; they are not uploaded or saved persistently.",
    igAccessHelp: "You can open this tool without signing in. Instagram may require login or restrict access to lists. Results appear only after both lists have been read completely.",
    igRefresh: "Check again",
    igStop: "Stop",
    igSearch: "Search names or usernames",
    igFollowing: "Following",
    igFollowers: "Followers",
    igCategories: "Follow relationships",
    igNotFollowingBack: "Not following back",
    igMutual: "Mutual",
    igFollowersOnly: "Followers only",
    igNotFollowingBackHelp: "Accounts followed by @{username} that do not follow this profile back.",
    igMutualHelp: "Accounts that follow @{username} and are followed back by this profile.",
    igFollowersOnlyHelp: "Accounts that follow @{username} but are not followed back by this profile.",
    igEmpty: "No matching accounts.",
    igPrevious: "Previous",
    igNext: "Next",
    igClearCurrent: "Clear this profile’s scan data",
    igClearAll: "Clear all results",
    igClearedCurrent: "Cleared the saved result for this profile.",
    igClearedAll: "Cleared all Instagram list results from this browser session.",
    igUnfollow: "Unfollow",
    igUnfollowedAction: "Unfollowed",
    igUnfollowAccount: "Unfollow @{username}",
    igOpeningUnfollowConfirmation: "Checking @{username} in Following…",
    igConfirmOnInstagram: "Instagram’s confirmation is open for @{username}. Choose Unfollow or Cancel in the page.",
    igUnfollowVerified: "Instagram no longer lists @{username} in Following.",
    igUnfollowUnchanged: "No unfollow was confirmed for @{username}. You can try again if needed.",
    igReadingProfile: "Reading profile…",
    igProgress: "Reading the page lists. This may take a while.",
    igComplete: "Both lists have been checked. Relationships may change after this check.",
    igStopped: "Stopped. Check again to read fresh lists.",
    igProfileOnly: "Open an Instagram user profile to use this tool. Posts, reels, and other pages are not supported.",
    igPageChanged: "The source page changed or closed. Open the tool again from the profile you want to check.",
    igSessionEnded: "This check has ended. Close and reopen the side panel to start again.",
    igUnavailable: "Instagram did not return usable list data. Try again later.",
    igLoginRequired: "Instagram requires you to sign in before it will provide these lists.",
    igAccessDenied: "Instagram has restricted access. Check the website for any login or account verification prompt before trying again.",
    igRateLimited: "Instagram has limited requests. Reading has stopped; please wait before trying again.",
    igIncomplete: "Instagram returned an incomplete list, or the lists changed during reading. No comparison is shown to avoid incorrect results. Try again later.",
    igTooLarge: "This profile exceeds the current limit of 20,000 accounts per list. No partial comparison is shown.",
    igTimedOut: "Instagram took too long to respond. Reading has stopped; try again later.",
    igBusy: "A request is still finishing. Please try again in a moment.",
    igOwnProfileOnly: "Unfollowing is available only on your own profile with the same account signed in.",
    igRelationshipChanged: "This relationship has changed. Check the lists again before taking action.",
    igUnfollowUncertain: "Instagram did not confirm the result. Check again before retrying; this action will not be repeated automatically.",
    appName: 'Cosmic Gemini',
    nativeScrollName: 'Native Scroll',
    noAutoplayName: 'No Autoplay',
    anyCopyName: 'Any Copy',
    anyCopyEnhancedName: 'Any Copy Enhanced',
    imageDownloadName: 'Image Download',
    videoDownloadName: 'Video Download',
    satellitesName: 'Satellites',
    satellitesGeneralFeatures: 'General features',
    satellitesSiteSpecificFeatures: 'Site-specific features',
    pageProtectionToolsLabel: 'Page controls',
    enableProductOnSiteTitle: 'Enable {product} on this site',
    disableProductOnSiteTitle: 'Disable {product} on this site',
    removeSiteOverrideTitle: '{product} has a site override · Click to follow the broader setting',
    useEnhancedOnSiteTitle: 'Use {product} Enhanced mode on this site',
    useStandardOnSiteTitle: 'Return {product} to Standard mode on this site',
    featureOnTitle: '{product} is on · Click to turn off',
    featureOffTitle: '{product} is off · Click to turn on',
    standardSiteTitle: 'Standard on this site · Click for Enhanced',
    removeEnhancedRuleTitle: 'Enhanced mode is set by {rule} · Click to remove this rule',
    enhancedUnavailableTitle: 'Remove this site from the whitelist before using Enhanced mode',
    anyCopyOffTitle: 'Enable Any Copy on this site',
    anyCopyOnTitle: 'Any Copy is active on this site · Click to turn off',
    anyCopyCoveredTitle: 'Any Copy is enabled by {rule} · Click to remove the matching rule and turn off',
    anyCopyEnhancedOffTitle: 'Open Any Copy Enhanced in this tab',
    anyCopyEnhancedOnTitle: 'Any Copy Enhanced is active in this tab · Click to close',
    anyCopyZhihuPauseTitle: 'Ad Marshal keeps Any Copy active on Zhihu · Click to pause it in this tab',
    anyCopyZhihuResumeTitle: 'Any Copy is paused in this tab · Click to resume',
    siteFeatureOffTitle: 'Enable {product} on this site',
    siteFeatureOnTitle: '{product} is active on this site · Click to turn off',
    siteFeatureCoveredTitle: '{product} is enabled by {rule} · Click to remove the matching rule and turn off',
    quickToolsLabel: 'Quick tools',
    allSettingsTitle: 'Open All Settings',
    imageStartTitle: 'Find images in this tab',
    imageOpenTitle: 'Open images found in this tab',
    videoStartTitle: 'Find videos in this tab',
    videoOpenTitle: 'Open videos found in this tab',
    videoStopTitle: 'Stop Video Download in this tab',
    videoRescanTitle: 'Scan this tab again',
    addWhitelistTitle: 'Add this site to the {product} whitelist',
    removeWhitelistTitle: 'Remove this site from the {product} whitelist',
    removeCoveredWhitelistTitle: 'Whitelisted by {rule} · Click to remove this rule',
    unsupportedTitle: 'This page is unavailable',
    settingsTitle: 'Open {product} settings',
    popupLabel: 'Cosmic Gemini controls',
    nativeScrollControlsLabel: 'Native Scroll controls',
    noAutoplayControlsLabel: 'No Autoplay controls',
    anyCopyControlsLabel: 'Any Copy controls',
    pageDisplayControlsLabel: 'Page Display controls',
    downloadToolsLabel: 'Download tools',
    settingsHeading: 'Settings',
    switchNativeSettings: 'Open Native Scroll settings',
    switchAutoplaySettings: 'Open No Autoplay settings',
    switchAnyCopySettings: 'Open Any Copy settings',
    switchImageDownloadSettings: 'Open Image Download settings',
    switchVideoDownloadSettings: 'Open Video Download settings',
    switchPageDisplaySettings: 'Open Page Display settings',
    enableGlobalProductTitle: 'Turn on {product} on all websites',
    disableGlobalProductTitle: 'Turn off {product} on all websites',
    switchSatellitesSettings: 'Open Satellites settings',
    switchAllSettings: 'Open All Settings',
    nativeStandardHeading: 'Native Scroll – Standard mode',
    autoplayStandardHeading: 'No Autoplay – Standard mode',
    nativeIntroPurpose: 'Keep browser scrolling in control across websites.',
    autoplayIntroPurpose: 'Stop video and audio that starts without your action.',
    nativeProtectionHelp: 'Enabled by default. Website settings can override this preference.',
    autoplayProtectionHelp: 'Enabled by default. Website settings can override this preference.',
    websiteBehaviorHeading: 'Website settings',
    nativeWebsiteBehaviorHelp: 'Choose how Native Scroll should behave on specific websites.',
    autoplayWebsiteBehaviorHelp: 'Choose how No Autoplay should behave on specific websites.',
    inactiveSitesHeading: 'Always inactive',
    standardSitesHeading: 'Always use Standard mode',
    enhancedSitesHeading: 'Always use Enhanced mode',
    inactiveSitesHelp: 'Keep this feature inactive at all times on matching websites.',
    standardSitesHelp: 'Use Standard mode at all times on matching websites.',
    enhancedSitesHelp: 'Use Enhanced mode at all times on matching websites.',
    sharedWhitelistHeading: 'Shared whitelist',
    sharedWhitelistHelp: 'Keep both Native Scroll and No Autoplay inactive on matching websites. Changes made here appear in both settings pages.',
    emptySharedWhitelist: 'The shared whitelist is empty.',
    nsnaWhitelistActiveTitle: 'Native Scroll and No Autoplay are inactive because this site matches the shared whitelist',
    websiteRuleLabel: 'Website',
    websiteBehaviorLabel: 'Behavior',
    changeBehaviorForRule: 'Change behavior for {rule}',
    anyCopyEnhancedTabHelp: 'Open Any Copy Enhanced from the popup when you want a clean, static reading view in the current tab. It remains limited to that tab and ends when you turn it off or close the tab.',
    enforcedSitesHeading: 'Any Copy sites',
    enforcedSitesHelp: 'Any Copy restores selection and preserves the text you copy on matching websites.',
    anyCopyIntroHelp: 'Restore text selection and copying while keeping clipboard content unchanged on selected websites.',
    anyCopySitesHeading: 'Any Copy sites',
    anyCopySitesHelp: 'Restore text selection, copy shortcuts, and unchanged clipboard content on matching websites.',
    currentTabOnlyLabel: 'On click',
    whitelistHeading: 'Whitelist',
    nativeWhitelistHelp: 'Native Scroll stays inactive on matching websites.',
    autoplayWhitelistHelp: 'No Autoplay stays inactive on matching websites. Video, audio, and Web Audio may autoplay there.',
    audioAllowHeading: 'Audio autoplay',
    audioAllowHelp: 'Keep audio autoplay blocked, allow it everywhere, or allow it only on selected websites. Video autoplay is controlled separately above.',
    audioAllowAllSitesHeading: 'Allow audio autoplay on all sites',
    audioAllowAllSitesHelp: 'Allow audio elements and Web Audio to start automatically on every website. Autoplaying videos remain blocked.',
    audioAllowedSitesHeading: 'Allowed websites',
    audioAllowedSitesHelp: 'Allow audio elements and Web Audio to start automatically only on matching websites.',
    anyCopyStandardHeading: 'Any Copy',
    siteActivationLabel: 'Site activation',
    anyCopyActivationHelp: 'Enable Any Copy for the current website from the extension popup. Exact hostnames or IP addresses are saved by default; wildcard domain rules can be added below.',
    rulePlaceholder: 'example.com, *.example.com, or 192.0.2.1',
    add: 'Add',
    removeRule: 'Remove {rule}',
    emptyInactiveSites: 'No websites are always inactive.',
    emptyStandardSites: 'No websites always use Standard mode.',
    emptyEnhancedSites: 'No websites always use Enhanced mode.',
    emptyEnforcedSites: 'Any Copy is not enabled on any website.',
    emptyAnyCopySites: 'Any Copy is not enabled on any website.',
    emptyAudioAllow: 'No websites may use audio autoplay.',
    exactHostnameHelp: 'example.com or an IP address matches that host only.',
    wildcardHostnameHelp: '*.example.com also matches the root domain and all of its subdomains.',
    invalidRule: 'Enter a valid hostname, IP address, or a wildcard such as *.example.com.',
    settingsSaveFailed: 'Could not save this setting. Please try again.',
    settingsResetFailed: 'Could not reset all settings. Please try again.',
    ruleSaveFailed: 'Could not save this rule. Please try again.',
    duplicateRule: 'That rule is already listed.',
    clearDomainRulesConfirm: "Clear all website rules in this card? This can't be undone.",
    ruleInputHelpHeading: 'Website rule input',
    accessControlInputHelpHeading: 'Access Control input',
    ruleInputHelpIntro: 'Enter a website rule using one of the formats below.',
    accessControlInputHelpIntro: 'Enter an address or a supported service alias using one of the formats below.',
    ruleInputBehaviorHelp: 'Choose the website behavior from the menu beside the input before adding the rule.',
    ruleInputRulesHeading: 'Accepted entries',
    ruleInputExactHelp: 'An exact hostname or IP address matches that host only.',
    ruleInputWildcardHelp: 'A wildcard such as *.example.com matches the root domain and all of its subdomains.',
    ruleInputExpansionHelp: 'A leading dot expands a multi-label domain to a wildcard. Supported multi-label eTLD entries expand in the same way.',
    accessControlInputDomainHelp: 'A domain such as example.com, with or without *., blocks the root domain and all of its subdomains.',
    accessControlInputIpHelp: 'An IPv4 or IPv6 address blocks that exact address on every port.',
    accessControlInputAliasesHeading: 'Site aliases',
    ruleInputShortcutsHeading: 'Shortcuts',
    ruleInputResetHelp: 'Alphabetize the website rules managed by this input.',
    ruleInputCleanHelp: 'Ask for confirmation, then clear the website rules managed by this card.',
    ruleInputLongPressHelp: 'Press and hold this button while the input is empty to alphabetize the list.',
    ruleInputQuestionHelp: 'Open this input help without saving a rule.',
    close: 'Close',
    languageHeading: 'Language',
    english: 'English',
    chinese: '简体中文',
    helpHeading: 'How it works',
    setupGuideHeading: 'Recommended setup',
    nativeSetupStepDefault: 'Leave Native Scroll active by default for a consistent scrolling experience.',
    nativeSetupStepExceptions: 'Add only websites that should always remain inactive or use a fixed mode.',
    nativeSetupStepEnhanced: 'Choose Enhanced mode only when Standard mode cannot keep the page from taking scrolling back.',
    autoplaySetupStepDefault: 'Leave No Autoplay active by default to stop media that starts on its own.',
    autoplaySetupStepExceptions: 'Add only websites that should always remain inactive or use a fixed mode.',
    autoplaySetupStepEnhanced: 'Choose Enhanced mode only when removing media elements is the desired result.',
    autoplaySetupStepAudio: 'Allow audio autoplay everywhere or on selected websites only when you want it.',
    nativeHelpStandard: 'Native Scroll intercepts website code that takes over wheel and trackpad gestures in Standard mode while preserving ordinary page controls and scrollable areas.',
    nativeHelpEnhanced: 'Enhanced mode also handles pages that simulate movement or repeatedly restore custom scrolling. Use it only for websites set to Always use Enhanced mode.',
    nativeHelpIndicator: 'The toolbar icon changes after Native Scroll suppresses scrolling code on the current page.',
    autoplayHelpStandard: 'No Autoplay stops media that starts without a direct action. Media you intentionally play remains available.',
    autoplayHelpEnhanced: 'Enhanced mode removes video and audio elements from websites set to Always use Enhanced mode.',
    autoplayHelpSound: 'Audio autoplay remains blocked unless you allow it for all sites or through a matching website rule. These audio permissions do not allow autoplaying video.',
    anyCopyHelpStandard: 'Any Copy restores text selection, keeps copy shortcuts available, and prevents websites from replacing copied content or adding promotional text.',
    anyCopyHelpEnhanced: 'Open Any Copy Enhanced for the current tab to place a static reading view over the original page. Turning it off restores the original page immediately without changing Any Copy.',
    imageDownloadActivationHelp: 'Open the extension popup and click Image Download to find images in the current tab. The workspace opens beside the page by default.',
    imageDownloadPreferencesHeading: 'Download preferences',
    imageDownloadPreferencesHelp: 'Choose where the workspace opens, along with its default format and batch-download behavior.',
    imageWorkspaceModeHeading: 'Workspace location',
    imageWorkspaceModeHelp: 'Keep the source page visible with the Side Panel, or use a separate tab.',
    imageWorkspaceSidePanel: 'Side panel',
    imageWorkspacePage: 'Separate tab',
    imageOutputFormatHeading: 'Default image format',
    imageOutputFormatHelp: 'Keep each original format or convert compatible images locally before downloading.',
    imageBatchModeHeading: 'Multiple-image downloads',
    imageBatchModeHelp: 'Place selected images in one ZIP file or send them to Chrome as separate files.',
    keepOriginalFormat: 'Keep original format',
    downloadAsZip: 'Download as ZIP',
    downloadSeparately: 'Download separately',
    imageDownloadHelpDetection: 'Image Download finds responsive images, lazy-loaded sources, linked originals, CSS images, frames, open shadow roots, inline SVG, canvas content, structured metadata, and image requests observed during the active session.',
    imageDownloadHelpOriginals: 'Related thumbnails and alternate formats are grouped together. The highest-quality verified source is selected by default while other available sizes remain selectable.',
    imageDownloadHelpBatch: 'The workspace provides previews, filters, sorting, selection, local format conversion, separate downloads, and local ZIP creation.',
    imageDownloadPrivacy: 'Image Download keeps page and image information only for the active tab session and does not save browsing or download history. Selected images are fetched from their source and processed locally.',
    videoDownloadActivationHelp: 'Open the extension popup and click Video Download to find downloadable media in the current tab.',
    clickToEnableLabel: 'On click',
    videoDownloadPreferencesHeading: 'Download preferences',
    videoDownloadPreferencesHelp: 'Choose how Video Download selects streams and starts Chrome downloads.',
    preferredQualityHeading: 'Preferred quality',
    preferredQualityHelp: 'The closest available quality is used when a stream offers several variants.',
    qualityBest: 'Best available',
    askWhereToSaveHeading: 'Ask where to save',
    askWhereToSaveHelp: 'Show Chrome’s save dialog before each file is downloaded.',
    videoDownloadHelpDetection: 'Video Download combines network requests, player state, streaming manifests, embedded frames, and dedicated support for compatible video services.',
    videoDownloadHelpFormats: 'Direct files, compatible HLS and DASH streams, separate video and audio tracks, subtitles, and live snapshots are processed locally. Standard AES-128 HLS and supported wrapped HLS playlists are also handled.',
    videoDownloadHelpSession: 'Detection applies only to the current tab. It continues through same-site navigation and ends when the tab changes to another website, closes, or you stop it.',
    videoDownloadPrivacy: 'Video Download keeps detected media information only for the active tab session and does not save browsing or download history. Selected media is fetched from its source and processed locally.',
    back: 'Back',
    download: 'Download',
    videoScanningHelp: 'Looking for video. If nothing appears, play the video once and reopen this panel.',
    videoUnavailablePage: 'Video Download cannot inspect this page.',
    videoTwitterOpenPost: 'Click the download arrow on a video to choose it, or open a post’s detail page.',
    videoTwitterLoading: 'Finding videos and available qualities…',
    videoTwitterEmpty: 'No downloadable video was found for this post. Once the post has loaded, try Refresh. Make sure you can view it on X / Twitter.',
    videoStopped: 'Video Download has stopped in this tab.',
    videoFound: 'Download options: {count}',
    videoMediaFound: 'Videos found: {count}',
    videoItem: 'Video {index}',
    videoQuality: 'Quality',
    videoGroup: 'Video',
    audioGroup: 'Audio',
    subtitleGroup: 'Subtitles',
    videoAudioOnly: 'Audio only',
    videoAudioFile: 'Audio file',
    otherFormats: 'Other formats ({count})',
    videoStream: 'HLS stream',
    videoCombinedStream: 'Video + audio',
    videoDashStream: 'DASH stream',
    videoSubtitles: 'Subtitles',
    videoProtectedMedia: 'Protected media',
    videoFile: 'Video file',
    videoLiveSnapshot: 'Current live segment window',
    videoUnavailableFormat: 'Unavailable',
    videoPreparing: 'Preparing {progress}%',
    videoCancelProcessingTitle: 'Cancel processing',
    videoDownloading: 'Downloading',
    videoDownloaded: 'Downloaded',
    videoRetry: 'Retry',
    videoDownloadFailedHelp: 'The selected video could not be downloaded.',
    imageWorkspaceActions: 'Image Download actions',
    imageSearchLabel: 'Search images',
    imageFiltersHeading: 'Filters',
    activeFilterCount: '{count} active filters',
    imageSearchPlaceholder: 'Search filename, description, or address',
    imageTypeLabel: 'Type',
    allTypes: 'All types',
    imageLayoutLabel: 'Layout',
    allLayouts: 'All layouts',
    layoutWide: 'Wide',
    layoutTall: 'Tall',
    layoutSquare: 'Square',
    minimumWidth: 'Min width',
    minimumHeight: 'Min height',
    sortBy: 'Sort',
    sortLargest: 'Largest first',
    sortSmallest: 'Smallest first',
    sortPageOrder: 'Page order',
    clearFilters: 'Clear filters',
    selectVisible: 'Select visible',
    clearSelection: 'Clear selection',
    imageOutputFormat: 'Image output format',
    imageBatchMode: 'Image batch mode',
    downloadSelected: 'Download selected',
    downloadSelectedCount: 'Download selected ({count})',
    imageNoResults: 'No matching images',
    imageNoResultsHelp: 'Try clearing the filters or use Full-page scan to load images that appear later on the page.',
    imageFocusSourceTitle: 'Return to the source page',
    imageOpenPageTitle: 'Open in a separate tab',
    imageCaptureAreaTitle: 'Capture an area of the visible page',
    imageRescanTitle: 'Scan the current page again',
    imageDeepScanTitle: 'Scan the full page, including lazy-loaded images',
    imageStopTitle: 'Stop Image Download in this tab',
    imageSessionStarting: 'Starting Image Download…',
    imageFindingImages: 'Finding images…',
    imageCheckingSources: 'Found {count} images · checking available sources…',
    imageScanning: 'Scanning the current page…',
    imageDeepScanning: 'Loading and scanning the full page…',
    imageScanTimedOut: 'The page took too long to scan. Try scanning again.',
    imageUnavailablePage: 'Image Download cannot inspect this page.',
    imageSessionStopped: 'Image Download has stopped in the source tab.',
    imageOriginalPreferred: 'The best available source is selected by default for each image.',
    imageResults: 'Images shown: {count}',
    imageNumber: 'Image {number}',
    selectImage: 'Select {name}',
    imageVariantLabel: 'Available sizes and formats',
    alternateImage: 'Alternate image',
    downloadImageTitle: 'Download this image',
    imageDownloadStarted: 'Started downloading {count} image(s).',
    imageDownloadFailed: 'The selected images could not be downloaded.',
    unknownFormat: 'Image',
    websiteKnowledgeName: "Website Knowledge Control",
    websiteKnowledgeDescription: "Control the language and regional format, time zone, and privacy preference sent to websites. Turn on only the categories you want to change; the others follow your browser and device.",
    websiteKnowledgeOptions: "Browser information to adjust",
    websiteKnowledgeLanguages: "Language and regional formats",
    websiteKnowledgeLanguagesHelp: "Set the language used for requests and browser information together with the default regional formats for dates, numbers, and other values. Websites can still request a specific locale.",
    websiteKnowledgeTimeZone: "Time zone",
    websiteKnowledgeTimeZoneHelp: "Use the selected time zone for browser date and time information, including daylight saving time.",
    websiteKnowledgeGlobalPrivacyControl: "Global Privacy Control",
    websiteKnowledgeGlobalPrivacyControlHelp: "Send the Global Privacy Control signal to ask websites not to sell or share your personal data.",
    websiteKnowledgePrivacy: "Adjustments run locally without reading page content or changing your system settings. Websites receive the selected values through the browser.",
    clipboardProtectName: 'Clipboard Protect',
    clipboardProtectDescription: 'Keep the text you select free of extra content added by a website when you copy it. Clipboard Protect blocks copy-event changes such as appended links, credits, and promotional messages while preserving available formatting. Editable areas keep their own copy behavior. When Any Copy is active on a page, it takes priority and Clipboard Protect steps aside.',
    clipboardProtectPrivacy: 'Selected content is processed locally during copying. Clipboard Protect does not read your existing clipboard, store copied content, or send it anywhere.',
    accessControlName: 'Access Control',
    accessControlDescription: 'Block visits to selected domains, all of their subdomains, and exact IP addresses. Rule changes take effect when a matching page is reloaded or opened again.',
    accessControlBlockedDomainsHeading: 'Blocked addresses',
    accessControlDomainPlaceholder: 'example.com or 192.0.2.1',
    accessControlEmptyDomains: 'No addresses are blocked.',
    accessControlInvalidDomain: 'Enter a valid domain or IP address.',
    accessControlSubdomainsSuffix: 'and all its subdomains',
    accessControlTemporaryVisits: 'Allow one-time visits from the extension popup.',
    accessControlAllowVisitTitle: 'Allow this visit',
    accessControlPrivacy: 'Access Control applies local browser network rules to the domains and IP addresses you list. It does not record attempted visits or send the list anywhere.',
    mailtoCaptureName: 'Mailto Capture',
    mailtoCaptureDescription: 'Stop mailto links from opening your system mail app before you can inspect them. Mailto Capture shows recipients, CC and BCC addresses, the subject, message, and other included fields in a compact page preview for copying. It also supports external protocol links using “tel:” and “sms:”.',
    mailtoCapturePrivacy: 'Mailto Capture handles email and telephone links on your device and does not record email addresses, telephone numbers, or message content.',
    chineseResponseClaudeName: 'Chinese Response Display Optimization for Claude',
    chineseResponseClaudeDescription: 'Convert half-width punctuation marks in Claude’s Chinese replies to the corresponding full-width Chinese forms. Consistent spaces are also added around Latin letters, numbers, and related symbols. Code, links, formulas, and editable text remain unchanged.',
    claudeBrowserIdentityHelp: 'Keep selected browser identity signals consistent for Claude use in the United States.',
    chineseResponseClaudePrivacy: 'Processing runs locally on supported Claude and Anthropic pages. The extension does not separately send or retain reply text or browser identity information.',
    chineseResponseClaudeOffTitle: 'Turn on Chinese Response Display Optimization for Claude',
    chineseResponseClaudeOnTitle: 'Chinese Response Display Optimization for Claude is on · Click to turn off',
    chineseResponseClaudeActiveTitle: 'Chinese Response Display Optimization for Claude has adjusted this page · Click to turn off',
    pageDisplayName: 'Page Display',
    pageDisplayDescription: 'Adjust colors across complete webpages, including images and video, with independent visual controls.',
    pageDisplayHelpEffects: 'Page Display applies Reduce White Point and Greyscale across complete webpages, including images and video.',
    pageDisplayHelpRestore: 'Turn off Page Display to restore every page while keeping your selected adjustments for the next time you enable it.',
    reduceWhitePointName: 'Reduce White Point',
    reduceWhitePointHelp: 'Reduce the intensity of bright colors across webpages for more comfortable viewing.',
    reduceWhitePointReductionHeading: 'Reduction',
    reduceWhitePointReductionHelp: 'Choose how strongly page brightness is reduced.',
    greyscaleName: 'Greyscale',
    greyscaleHelp: 'Render webpages in shades of grey.',
    pageDisplayPrivacy: 'Page Display applies visual adjustments locally without reading or retaining page content.',
    xhsImageDarkModeName: 'XHS Image Dark Mode',
    xhsImageDarkModeSettingsName: 'XHS Image Dark Mode (beta)',
    experimentalFeature: 'This is an experimental feature.',
    xhsImageDarkModeDescription: 'Make bright text images easier to view when a page-wide dark mode is active on Xiaohongshu.',
    xhsImageDarkModeScopeDescription: 'View text cards and chat screenshots in posts and comments with less glare, while leaving photos unchanged.',
    xhsImageDarkModeControlsDescription: 'Switch individual images or an entire post between light and dark display, or pause the feature for a user’s profile.',
    xhsImageDarkModeOverrideHeading: 'Always on',
    xhsImageDarkModeOverrideHelp: 'Adjust matching images even when a page-wide dark mode is not detected.',
    xhsImageDarkModeControlHeading: 'Show image controls',
    xhsImageDarkModeControlHelp: 'After opening a post, show a small button beside the page count. Press and hold to alternate the complete post between dark and light display; click to restore automatic recognition. An opened comment image uses a separate single-image control.',
    xhsImageDarkModeOpacityHeading: 'Button opacity',
    xhsImageDarkModeOpacityHelp: 'Set the idle opacity of the image button.',
    xhsImageDarkModePrivacy: 'Images are processed on your device and are never uploaded. Temporary results are cleared when the page closes.',
    xhsImageDarkModeOffTitle: 'Turn on XHS Image Dark Mode for Xiaohongshu',
    xhsImageDarkModeWaitingTitle: 'XHS Image Dark Mode is on · Waiting for a page-wide dark mode',
    xhsImageDarkModeActiveTitle: 'XHS Image Dark Mode is active · Click to turn off',
    biliDailyLoginName: 'Bili Daily Login',
    adMarshalName: 'Ad Marshal',
    adMarshalDescription: 'Stop persistent advertising, reporting, and tracking components from repeatedly reconnecting on managed sites. Ad Marshal applies lightweight, site-specific rules that neutralize known loaders and request loops at the source and hide related ad elements.',
    adMarshalManagedSitesHeading: 'Managed sites',
    adMarshalTencentNews: 'news.qq.com (including www.qq.com)',
    adMarshalZhihu: 'zhihu.com and subdomains',
    adMarshalPrivacy: 'Ad Marshal runs locally only on the sites you select. It does not record your browsing activity.',
    satellitesHelpHeading: 'About Satellites',
    satellitesHelpIntro: 'Satellites groups focused tools that do not need a permanent place in the popup. Each tool works independently, and site-specific controls appear only where they apply.',
    satellitesOverviewHelp: 'Choose the small, independent tools you may want to use.',
    disabledInIncognito: 'Disabled in Incognito',
    disabledByDefaultInIncognito: 'Disabled by default in Incognito.',
    biliDailyLoginDescription: 'Bilibili awards one coin when a signed-in account completes its daily check-in. Bili Daily Login handles that check-in automatically whenever Chrome is available.',
    biliDailyLoginPrivacyHeading: 'Privacy',
    biliDailyLoginPrivacy: 'Bili Daily Login never monitors when you visit Bilibili. It connects only to Bilibili account services while the computer is awake and Chrome is running, using the account already signed in to Chrome without reading or storing your password. A completion date and limited scheduling data prevent duplicate checks.',
    privacyHeading: 'Privacy',
    nativePrivacy: 'Native Scroll runs locally and does not send browsing data. Website rules contain only the hostnames or IP addresses you choose.',
    autoplayPrivacy: 'No Autoplay runs locally and does not send browsing data. Website rules contain only the hostnames or IP addresses you choose.',
    anyCopyPrivacy: 'Any Copy and Any Copy Enhanced run locally and never send copied text or browsing data. Website rules contain only the hostnames or IP addresses you choose. Any Copy Enhanced keeps its current-tab state only for that browser session.',
    allSettingsName: 'All Settings',
    allSettingsIntro: 'Open every Cosmic Gemini product setting from one place.',
    allSettingsHelpHeading: 'Settings collection',
    allSettingsHelp: 'Choose a product to open its dedicated settings. Each product keeps its controls and website rules in its own section.',
    allSettingsNativeDescription: 'Configure scrolling protection and website rules.',
    allSettingsAutoplayDescription: 'Configure media blocking and audio autoplay permissions.',
    allSettingsAnyCopyDescription: 'Manage Any Copy websites and learn how Any Copy Enhanced works in the current tab.',
    allSettingsImageDescription: 'Choose the image workspace and download defaults.',
    allSettingsVideoDescription: 'Choose preferred video quality and download behavior.',
    allSettingsPageDisplayDescription: 'Adjust webpage brightness and color.',
    allSettingsSatellitesDescription: 'Manage smaller auxiliary tools.',
    resetAllSettingsHeading: 'Reset settings',
    resetAllSettingsHelp: 'Restore every product setting and website rule to its default.',
    resetAllSettingsAction: 'Reset all settings',
    resetAllSettingsConfirmHeading: 'Reset all settings?',
    resetAllSettingsConfirmHelp: 'This restores every setting, removes saved website rules, and stops current temporary sessions. Files already downloaded are unaffected.',
    cancel: 'Cancel',
    reset: 'Reset',
    version: 'Version {version}',
    unavailable: 'Unable to update Cosmic Gemini.'
  },
  'zh-CN': {
    documentPreviewName: "Document Preview",
    documentPreviewDescription: "在浏览器中直接预览 .docx 文档，无需先保存文件。阅读时可切换深浅色模式，需要时也可下载原文件。",
    documentPreviewPrivacy: "文档仅在本机处理，不会上传至其他服务。该网站的最后一个标签页关闭或离开网站后，临时文件与本次操作偏好会被清除。每份文件的缓存也会在其最后一个预览页关闭 10 小时后清除，两者以先到者为准。",
    documentPreviewAction: "预览",
    documentZoom: "文档缩放",
    documentZoomOut: "缩小 10%",
    documentZoomIn: "放大 10%",
    documentZoomReset: "恢复至 100%",
    documentDownloadAction: "下载",
    documentClose: "关闭",
    documentRemember: "本网站本次均执行所选操作",
    documentActionFailed: "未能完成此操作，请重试。",
    documentLoading: "正在准备文档…",
    documentLayoutNote: "内容预览：复杂格式可能与 Word 中有所不同。",
    documentExpired: "此预览已过期，请打开来源网站并重新选择文档。",
    documentRenderFailed: "暂时无法显示此文档，您仍可下载原文件。",
    documentDownloadStarted: "已交由 Chrome 下载文件。",
    documentResetChoice: "Document Preview：{action}。点击恢复每次询问。",
    documentAutoPreview: "本网站本次始终预览",
    documentAutoDownload: "本网站本次始终下载",
    documentAppearance: "外观",
    documentAppearanceHelp: "选择预览的默认外观。在预览中切换后，该网站会沿用所选外观，直到其最后一个标签页关闭或离开。",
    documentAppearanceAuto: "自动",
    documentAppearanceLight: "浅色",
    documentAppearanceDark: "深色",
    documentThemeAuto: "默认",
    documentThemeFollow: "使用设置页中选择的外观",
    documentThemeLight: "切换为浅色模式",
    documentThemeDark: "切换为深色模式",
    langGoogleName: "Serch Result Language Designate for Google Search",
    langGoogleDescription: "在 Google 搜索词中使用“lang:”指定搜索结果的语言，支持同时选择多种语言，适用于网页、视频、图片等搜索分类。",
    langGooglePrivacy: "搜索网址仅在本机处理，不会记录搜索历史，也不会将搜索内容发送给其他服务。",
    igCloseDialog: "请先关闭 Instagram 中已打开的弹窗，再重新检查。",
    igListChanged: "列表搜索内容在读取期间发生了变化。请清空搜索内容后重新检查。",
    followListInstagramName: "Following/Follower List Check for Instagram",
    followListInstagramDescription: "在侧边栏中对比 Instagram 用户主页的关注与粉丝列表，查看未回关、互相关注以及尚未关注的粉丝。在自己的主页上，本工具可以为未回关账号打开 Instagram 的确认对话框，由你决定是否取消关注。",
    followListInstagramHelp: "打开 Instagram 用户主页后，点击插件控制窗口中的 IG± 图标按钮即可开始。收起侧边栏后仍会继续读取，重新打开即可查看进度或结果；点击“停止”可结束检查。",
    followListInstagramPrivacy: "本功能读取当前标签页中 Instagram 显示的列表，并在本地对比。完整结果仅保留于本次浏览器会话，退出浏览器后即会清除，不会上传或持久保存。",
    igAccessHelp: "无需登录即可打开本工具，但 Instagram 可能要求登录或限制列表访问。只有完整读取两份列表后才会显示对比结果。",
    igRefresh: "重新检查",
    igStop: "停止",
    igSearch: "搜索名称或用户名",
    igFollowing: "已关注",
    igFollowers: "粉丝",
    igCategories: "关注关系",
    igNotFollowingBack: "未回关",
    igMutual: "互相关注",
    igFollowersOnly: "尚未关注的粉丝",
    igNotFollowingBackHelp: "@{username} 关注了对方，但对方尚未回关的账号。",
    igMutualHelp: "与 @{username} 互相关注的账号。",
    igFollowersOnlyHelp: "关注了 @{username}，但尚未被该用户回关的账号。",
    igEmpty: "没有符合条件的账号。",
    igPrevious: "上一页",
    igNext: "下一页",
    igClearCurrent: "清除当前主页识别数据",
    igClearAll: "清除所有识别数据",
    igClearedCurrent: "已清除当前主页的识别结果。",
    igClearedAll: "已清除本次浏览器会话中的所有 Instagram 列表识别结果。",
    igUnfollow: "取消关注",
    igUnfollowedAction: "已取关",
    igUnfollowAccount: "取消关注 @{username}",
    igOpeningUnfollowConfirmation: "正在关注列表中检查 @{username}…",
    igConfirmOnInstagram: "Instagram 已在网页中打开 @{username} 的确认对话框，请在网页中选择“取消关注”或“取消”。",
    igUnfollowVerified: "Instagram 的关注列表中已没有 @{username}。",
    igUnfollowUnchanged: "未确认 @{username} 已被取关；如有需要，可以再次尝试。",
    igReadingProfile: "正在读取主页…",
    igProgress: "正在读取网页列表，可能需要一些时间。",
    igComplete: "已完成两份列表的对比。关注关系可能在检查后发生变化。",
    igStopped: "已停止。点击“重新检查”可重新读取列表。",
    igProfileOnly: "请在 Instagram 用户主页使用本工具。帖子、短视频详情及其他页面暂不支持。",
    igPageChanged: "来源页面已切换或关闭。请在要检查的用户主页上重新打开本工具。",
    igSessionEnded: "本次检查已结束。请关闭并重新打开侧边栏后再试。",
    igUnavailable: "Instagram 未返回可用的列表数据，请稍后再试。",
    igLoginRequired: "Instagram 要求登录后才能读取这些列表。",
    igAccessDenied: "Instagram 限制了访问。请先检查网站上是否有登录或账号验证提示，再尝试读取。",
    igRateLimited: "Instagram 暂时限制了请求，已停止读取。请过一段时间后再试。",
    igIncomplete: "Instagram 返回的列表不完整，或列表在读取期间发生了变化。为避免误判，暂不显示对比结果，请稍后再试。",
    igTooLarge: "该主页超出了每份列表 20,000 个账号的当前上限，暂不显示不完整的对比结果。",
    igTimedOut: "Instagram 响应超时，已停止读取，请稍后再试。",
    igBusy: "上一项请求仍在结束中，请稍后再试。",
    igOwnProfileOnly: "仅在自己的主页上，且登录账号与该主页一致时，才可取消关注。",
    igRelationshipChanged: "该账号的关注关系已发生变化，请重新检查列表后再操作。",
    igUnfollowUncertain: "Instagram 未确认操作结果。请重新检查后再决定是否重试，本工具不会自动重复此操作。",
    appName: 'Cosmic Gemini',
    nativeScrollName: 'Native Scroll',
    noAutoplayName: 'No Autoplay',
    anyCopyName: 'Any Copy',
    anyCopyEnhancedName: 'Any Copy 强力模式',
    imageDownloadName: 'Image Download',
    videoDownloadName: 'Video Download',
    satellitesName: 'Satellites',
    satellitesGeneralFeatures: '通用功能',
    satellitesSiteSpecificFeatures: '网站专用功能',
    pageProtectionToolsLabel: '页面功能',
    enableProductOnSiteTitle: '在此网站启用 {product}',
    disableProductOnSiteTitle: '在此网站停用 {product}',
    removeSiteOverrideTitle: '{product} 已单独设置，点击后改为遵循上级设置',
    useEnhancedOnSiteTitle: '在此网站使用 {product} 强力模式',
    useStandardOnSiteTitle: '在此网站恢复使用 {product} 标准模式',
    featureOnTitle: '{product} 已开启 · 点击关闭',
    featureOffTitle: '{product} 已关闭 · 点击开启',
    standardSiteTitle: '当前网站使用标准模式 · 点击改为强力模式',
    removeEnhancedRuleTitle: '规则 {rule} 已为当前网站开启强力模式 · 点击移除该规则',
    enhancedUnavailableTitle: '请先将当前网站移出白名单，再开启强力模式',
    anyCopyOffTitle: '在当前网站开启 Any Copy',
    anyCopyOnTitle: 'Any Copy 正在当前网站运行 · 点击关闭',
    anyCopyCoveredTitle: '规则 {rule} 已为当前网站开启 Any Copy · 点击移除该规则并关闭',
    anyCopyEnhancedOffTitle: '在当前标签页中打开 Any Copy 强力模式',
    anyCopyEnhancedOnTitle: 'Any Copy 强力模式正在当前标签页中运行 · 点击关闭',
    anyCopyZhihuPauseTitle: 'Ad Marshal 已为知乎持续开启 Any Copy · 点击在当前标签页暂停',
    anyCopyZhihuResumeTitle: 'Any Copy 已在当前标签页暂停 · 点击恢复',
    siteFeatureOffTitle: '在当前网站开启 {product}',
    siteFeatureOnTitle: '{product} 正在当前网站运行 · 点击关闭',
    siteFeatureCoveredTitle: '规则 {rule} 已为当前网站开启 {product} · 点击移除该规则并关闭',
    quickToolsLabel: '快捷工具',
    allSettingsTitle: '打开全部设置',
    imageStartTitle: '查找当前标签页中的图片',
    imageOpenTitle: '打开当前标签页的图片工作区',
    videoStartTitle: '查找当前标签页中的视频',
    videoOpenTitle: '查看当前标签页中找到的视频',
    videoStopTitle: '停止在当前标签页中查找视频',
    videoRescanTitle: '重新扫描当前标签页',
    addWhitelistTitle: '将当前网站加入 {product} 白名单',
    removeWhitelistTitle: '将当前网站移出 {product} 白名单',
    removeCoveredWhitelistTitle: '规则 {rule} 已将当前网站加入白名单 · 点击移除该规则',
    unsupportedTitle: '当前页面不支持此操作',
    settingsTitle: '打开 {product} 设置',
    popupLabel: 'Cosmic Gemini 控制项',
    nativeScrollControlsLabel: 'Native Scroll 控制项',
    noAutoplayControlsLabel: 'No Autoplay 控制项',
    anyCopyControlsLabel: 'Any Copy 控制项',
    pageDisplayControlsLabel: 'Page Display 控制项',
    downloadToolsLabel: '下载工具',
    settingsHeading: '设置',
    switchNativeSettings: '打开 Native Scroll 设置',
    switchAutoplaySettings: '打开 No Autoplay 设置',
    switchAnyCopySettings: '打开 Any Copy 设置',
    switchImageDownloadSettings: '打开 Image Download 设置',
    switchVideoDownloadSettings: '打开 Video Download 设置',
    switchPageDisplaySettings: '打开 Page Display 设置',
    enableGlobalProductTitle: '在所有网站中开启 {product}',
    disableGlobalProductTitle: '在所有网站中关闭 {product}',
    switchSatellitesSettings: '打开 Satellites 设置',
    switchAllSettings: '打开全部设置',
    nativeStandardHeading: 'Native Scroll – 标准模式',
    autoplayStandardHeading: 'No Autoplay – 标准模式',
    nativeIntroPurpose: '阻止网页接管滚动操作，保留 Chrome 原生的滚动体验。',
    autoplayIntroPurpose: '阻止网页在未经您操作的情况下播放视频或声音。',
    nativeProtectionHelp: '默认启用，您可以在下方为指定网站设置不同的运行方式。',
    autoplayProtectionHelp: '默认启用，您可以在下方为指定网站设置不同的运行方式。',
    websiteBehaviorHeading: '网站设置',
    nativeWebsiteBehaviorHelp: '为指定网站选择 Native Scroll 的固定运行方式。',
    autoplayWebsiteBehaviorHelp: '为指定网站选择 No Autoplay 的固定运行方式。',
    inactiveSitesHeading: '始终停用',
    standardSitesHeading: '始终使用标准模式',
    enhancedSitesHeading: '始终使用强力模式',
    inactiveSitesHelp: '符合规则的网站始终停用此功能。',
    standardSitesHelp: '符合规则的网站始终使用标准模式。',
    enhancedSitesHelp: '符合规则的网站始终使用强力模式。',
    sharedWhitelistHeading: '共用白名单',
    sharedWhitelistHelp: '白名单中的网站不会启用 Native Scroll 和 No Autoplay。这里的修改会同步显示在两个设置页面中。',
    emptySharedWhitelist: '共用白名单中尚无网站。',
    nsnaWhitelistActiveTitle: '当前网站在共用白名单中，Native Scroll 和 No Autoplay 均已停用',
    websiteRuleLabel: '网站',
    websiteBehaviorLabel: '运行方式',
    changeBehaviorForRule: '更改 {rule} 的运行方式',
    anyCopyEnhancedTabHelp: '需要简洁的静态阅读页面时，请从控制窗口为当前标签页打开 Any Copy 强力模式。该模式只在此标签页中运行，手动关闭或关闭标签页后即会结束。',
    enforcedSitesHeading: 'Any Copy 网站',
    enforcedSitesHelp: 'Any Copy 会在符合规则的网站上恢复文字选择，并确保复制内容不被网页篡改。',
    anyCopyIntroHelp: '恢复指定网站上的文字选择和复制操作，并确保剪贴板内容不被网页篡改。',
    anyCopySitesHeading: 'Any Copy 网站',
    anyCopySitesHelp: '在符合规则的网站上恢复文字选择、复制快捷键和原始剪贴板内容。',
    currentTabOnlyLabel: '点击时',
    whitelistHeading: '白名单',
    nativeWhitelistHelp: 'Native Scroll 不会在符合规则的网站上运行。',
    autoplayWhitelistHelp: 'No Autoplay 不会在符合规则的网站上运行。此类网站可以自动播放视频、声音和 Web Audio。',
    audioAllowHeading: '声音自动播放',
    audioAllowHelp: '声音默认会被拦截。您可以允许所有网站，或仅允许指定网站自动播放声音。视频自动播放仍由上方设置控制。',
    audioAllowAllSitesHeading: '允许所有网站自动播放声音',
    audioAllowAllSitesHelp: '允许所有网站自动播放音频元素和 Web Audio。自动播放的视频仍会被拦截。',
    audioAllowedSitesHeading: '允许的网站',
    audioAllowedSitesHelp: '仅允许符合规则的网站自动播放音频元素和 Web Audio。',
    anyCopyStandardHeading: 'Any Copy',
    siteActivationLabel: '按网站启用',
    anyCopyActivationHelp: '请在插件控制窗口中为当前网站开启 Any Copy。插件默认保存当前主机名或 IP 地址，您也可以在下方添加域名通配规则。',
    rulePlaceholder: 'example.com、*.example.com 或 192.0.2.1',
    add: '添加',
    removeRule: '移除 {rule}',
    emptyInactiveSites: '尚未设置始终停用的网站。',
    emptyStandardSites: '尚未设置始终使用标准模式的网站。',
    emptyEnhancedSites: '尚未设置始终使用强力模式的网站。',
    emptyEnforcedSites: '尚未在任何网站上开启 Any Copy。',
    emptyAnyCopySites: '尚未在任何网站上开启 Any Copy。',
    emptyAudioAllow: '尚未允许任何网站自动播放声音。',
    exactHostnameHelp: 'example.com 或 IP 地址仅匹配相应主机。',
    wildcardHostnameHelp: '*.example.com 同时匹配根域名及其所有子域名。',
    invalidRule: '请输入有效的主机名、IP 地址，或使用 *.example.com 这样的通配规则。',
    settingsSaveFailed: '未能保存这项设置，请重试。',
    settingsResetFailed: '未能重置全部设置，请重试。',
    ruleSaveFailed: '未能保存这条规则，请重试。',
    duplicateRule: '该规则已在列表中。',
    clearDomainRulesConfirm: '清除此卡片中的所有网站规则？此操作无法撤销。',
    ruleInputHelpHeading: '网站规则输入说明',
    accessControlInputHelpHeading: 'Access Control 输入说明',
    ruleInputHelpIntro: '此输入框接受以下格式的网站规则。',
    accessControlInputHelpIntro: '此输入框接受以下格式的地址或受支持的服务别名。',
    ruleInputBehaviorHelp: '添加规则前，请在输入框旁的菜单中选择该网站的运行方式。',
    ruleInputRulesHeading: '可输入的内容',
    ruleInputExactHelp: '输入完整主机名或 IP 地址时，仅匹配相应主机。',
    ruleInputWildcardHelp: '输入 *.example.com 这样的通配规则时，会匹配根域名及其所有子域名。',
    ruleInputExpansionHelp: '多级域名前加点号会自动扩展为通配规则；受支持的多级 eTLD 也会采用相同方式扩展。',
    accessControlInputDomainHelp: '输入 example.com 这样的域名时，无论是否带有 *.，都会阻止根域名及其所有子域名。',
    accessControlInputIpHelp: '输入 IPv4 或 IPv6 地址时，会阻止该地址所有端口上的访问。',
    accessControlInputAliasesHeading: '网站别名',
    ruleInputShortcutsHeading: '快捷指令',
    ruleInputResetHelp: '将此输入框管理的网站规则按字母顺序重新排列。',
    ruleInputCleanHelp: '二次确认后，清除此卡片管理的全部网站规则。',
    ruleInputLongPressHelp: '输入框为空时长按此按钮，可将列表按字母顺序重新排列。',
    ruleInputQuestionHelp: '打开当前输入框的说明面板，不会保存为网站规则。',
    close: '关闭',
    languageHeading: '语言',
    english: 'English',
    chinese: '简体中文',
    helpHeading: '工作方式',
    setupGuideHeading: '建议设置顺序',
    nativeSetupStepDefault: '建议保持 Native Scroll 默认启用，让日常滚动体验更加一致。',
    nativeSetupStepExceptions: '仅添加需要始终停用或固定使用某种模式的网站。',
    nativeSetupStepEnhanced: '只有标准模式无法阻止网页重新接管滚动时，才选择始终使用强力模式。',
    autoplaySetupStepDefault: '建议保持 No Autoplay 默认启用，拦截网页擅自播放的媒体。',
    autoplaySetupStepExceptions: '仅添加需要始终停用或固定使用某种模式的网站。',
    autoplaySetupStepEnhanced: '只有确实需要移除媒体元素时，才选择始终使用强力模式。',
    autoplaySetupStepAudio: '仅在需要时允许所有网站或指定网站自动播放声音。',
    nativeHelpStandard: 'Native Scroll 在标准模式下会拦截网页对滚轮和触控板手势的接管，同时保留普通页面控件和可滚动区域的正常操作。',
    nativeHelpEnhanced: '强力模式还会处理模拟页面移动或反复恢复自定义滚动的网页。请仅为确有需要的网站选择“始终使用强力模式”。',
    nativeHelpIndicator: 'Native Scroll 在当前页面拦截滚动代码后，工具栏图标会随之变化。',
    autoplayHelpStandard: 'No Autoplay 会阻止未经您操作便开始播放的媒体。您主动播放的内容仍可正常使用。',
    autoplayHelpEnhanced: '强力模式会从选择“始终使用强力模式”的网站中移除视频和音频元素。',
    autoplayHelpSound: '除非您允许所有网站或符合规则的网站自动播放声音，否则 No Autoplay 会继续拦截。声音播放权限不会放行自动播放的视频。',
    anyCopyHelpStandard: 'Any Copy 会恢复文字选择和复制快捷键，并阻止网页替换复制内容或添加推广文字。',
    anyCopyHelpEnhanced: '为当前标签页打开 Any Copy 强力模式后，插件会在原网页上方生成静态阅读页面。关闭后会立即恢复原网页，不会改变 Any Copy 的启用状态。',
    imageDownloadActivationHelp: '请打开插件控制窗口，点击 Image Download 查找当前标签页中的图片。图片工作区默认会在网页旁的侧边栏中打开。',
    imageDownloadPreferencesHeading: '下载设置',
    imageDownloadPreferencesHelp: '设置图片工作区的打开位置、默认图片格式和批量下载方式。',
    imageWorkspaceModeHeading: '打开位置',
    imageWorkspaceModeHelp: '使用侧边栏可以保留原网页，也可以选择在独立标签页中打开。',
    imageWorkspaceSidePanel: '侧边栏',
    imageWorkspacePage: '独立标签页',
    imageOutputFormatHeading: '默认图片格式',
    imageOutputFormatHelp: '保留图片原格式，或在下载前于本地转换兼容的图片。',
    imageBatchModeHeading: '多图下载方式',
    imageBatchModeHelp: '将选中的图片放入一个 ZIP 文件，或分别交给 Chrome 下载。',
    keepOriginalFormat: '保留原格式',
    downloadAsZip: '下载为 ZIP',
    downloadSeparately: '分别下载',
    imageDownloadHelpDetection: 'Image Download 会查找响应式图片、懒加载来源、原图链接、CSS 图片、嵌入式页面、开放的 Shadow DOM、内联 SVG、Canvas 内容和结构化数据，也会识别当前会话中出现的图片请求。',
    imageDownloadHelpOriginals: '插件会将同一图片的缩略图、不同尺寸和其他格式归在一起，默认选择经过识别的最高质量来源，同时保留其他可选版本。',
    imageDownloadHelpBatch: '图片工作区提供预览、筛选、排序、批量选择、本地格式转换、分别下载和本地 ZIP 打包。',
    imageDownloadPrivacy: 'Image Download 只会在当前标签页的临时会话中保留页面与图片信息，不会保存浏览记录或下载历史。选中的图片会从原网站获取，并在本地完成处理。',
    videoDownloadActivationHelp: '请打开插件控制窗口，点击 Video Download 查找当前标签页中可以下载的视频。',
    clickToEnableLabel: '点击时',
    videoDownloadPreferencesHeading: '下载设置',
    videoDownloadPreferencesHelp: '设置 Video Download 选择视频流和开始下载时使用的方式。',
    preferredQualityHeading: '首选画质',
    preferredQualityHelp: '视频流提供多种画质时，插件会选择最接近该设置的一项。',
    qualityBest: '最高可用画质',
    askWhereToSaveHeading: '下载前选择保存位置',
    askWhereToSaveHelp: '每次下载前显示 Chrome 的文件保存窗口。',
    videoDownloadHelpDetection: 'Video Download 会综合分析网络请求、播放器状态、视频流清单和嵌入式页面，并针对兼容的视频服务进行识别。',
    videoDownloadHelpFormats: '插件会在本地处理视频文件、兼容的 HLS 与 DASH 视频流、分离的音视频轨道、字幕和直播片段，也支持标准 AES-128 HLS 与部分经过封装的 HLS 清单。',
    videoDownloadHelpSession: '视频查找仅在当前标签页中启用。站内跳转不会中断，前往其他网站、关闭标签页或手动停止后会自动结束。',
    videoDownloadPrivacy: 'Video Download 只会在当前标签页的临时会话中保留检测到的媒体信息，不会保存浏览记录或下载历史。选中的媒体会从原网站获取，并在本地完成处理。',
    back: '返回',
    download: '下载',
    videoScanningHelp: '正在查找视频。如果没有出现结果，请播放一次视频后重新打开此页面。',
    videoUnavailablePage: 'Video Download 无法检查当前页面。',
    videoTwitterOpenPost: '请点击视频右上角的下载箭头选择视频，或打开帖子的详情页。',
    videoTwitterLoading: '正在查找当前帖子的视频及可用清晰度…',
    videoTwitterEmpty: '未找到当前帖子中可下载的视频。请确认您能在 X / Twitter 查看该帖子，待帖子加载完成后点击刷新重试。',
    videoStopped: '已停止在当前标签页中查找视频。',
    videoFound: '可下载选项：{count}',
    videoMediaFound: '发现 {count} 个视频',
    videoItem: '视频 {index}',
    videoQuality: '清晰度',
    videoGroup: '视频',
    audioGroup: '音频',
    subtitleGroup: '字幕',
    videoAudioOnly: '仅音频',
    videoAudioFile: '音频文件',
    otherFormats: '其他格式（{count}）',
    videoStream: 'HLS 视频流',
    videoCombinedStream: '视频与音频',
    videoDashStream: 'DASH 视频流',
    videoSubtitles: '字幕',
    videoProtectedMedia: '受保护媒体',
    videoFile: '视频文件',
    videoLiveSnapshot: '当前直播片段',
    videoUnavailableFormat: '暂不支持',
    videoPreparing: '正在处理 {progress}%',
    videoCancelProcessingTitle: '取消处理',
    videoDownloading: '正在下载',
    videoDownloaded: '下载完成',
    videoRetry: '重试',
    videoDownloadFailedHelp: '无法下载所选视频。',
    imageWorkspaceActions: 'Image Download 操作',
    imageSearchLabel: '搜索图片',
    imageFiltersHeading: '筛选',
    activeFilterCount: '已启用 {count} 项筛选条件',
    imageSearchPlaceholder: '搜索文件名、说明或地址',
    imageTypeLabel: '格式',
    allTypes: '全部格式',
    imageLayoutLabel: '方向',
    allLayouts: '全部方向',
    layoutWide: '横向',
    layoutTall: '纵向',
    layoutSquare: '方形',
    minimumWidth: '最小宽度',
    minimumHeight: '最小高度',
    sortBy: '排序',
    sortLargest: '尺寸从大到小',
    sortSmallest: '尺寸从小到大',
    sortPageOrder: '网页顺序',
    clearFilters: '清除筛选',
    selectVisible: '选择当前结果',
    clearSelection: '清除选择',
    imageOutputFormat: '图片输出格式',
    imageBatchMode: '图片批量下载方式',
    downloadSelected: '下载所选图片',
    downloadSelectedCount: '下载所选图片（{count}）',
    imageNoResults: '没有符合条件的图片',
    imageNoResultsHelp: '您可以清除筛选条件，或使用完整扫描加载网页后续出现的图片。',
    imageFocusSourceTitle: '返回原网页',
    imageOpenPageTitle: '在独立标签页中打开',
    imageCaptureAreaTitle: '截取当前可见网页中的区域',
    imageRescanTitle: '重新扫描当前页面',
    imageDeepScanTitle: '完整扫描网页并加载懒加载图片',
    imageStopTitle: '停止在当前标签页中查找图片',
    imageSessionStarting: '正在启动 Image Download…',
    imageFindingImages: '正在查找图片…',
    imageCheckingSources: '已找到 {count} 张图片，正在检查可用来源…',
    imageScanning: '正在扫描当前页面…',
    imageDeepScanning: '正在加载并扫描完整网页…',
    imageScanTimedOut: '扫描网页所需时间过长，请重新扫描。',
    imageUnavailablePage: 'Image Download 无法检查当前页面。',
    imageSessionStopped: '原标签页中的 Image Download 已停止。',
    imageOriginalPreferred: '每组图片均会默认选择质量最高的可用来源。',
    imageResults: '当前显示 {count} 张图片',
    imageNumber: '图片 {number}',
    selectImage: '选择{name}',
    imageVariantLabel: '可用尺寸与格式',
    alternateImage: '其他版本',
    downloadImageTitle: '下载该图片',
    imageDownloadStarted: '已开始下载 {count} 张图片。',
    imageDownloadFailed: '无法下载所选图片。',
    unknownFormat: '图片',
    websiteKnowledgeName: "Website Knowledge Control",
    websiteKnowledgeDescription: "自行设置向网站提供的语言与地区格式、时区和隐私偏好信息。只需勾选要调整的项目，未勾选的项目仍使用浏览器和设备的原有设置。",
    websiteKnowledgeOptions: "要调整的浏览器信息",
    websiteKnowledgeLanguages: "语言与地区格式",
    websiteKnowledgeLanguagesHelp: "统一设置网络请求与浏览器信息所使用的语言，以及日期、数字等内容的默认地区格式。网站明确指定地区时，仍使用其指定的格式。",
    websiteKnowledgeTimeZone: "时区",
    websiteKnowledgeTimeZoneHelp: "让浏览器的日期和时间信息使用所选时区，并随该时区的夏令时规则调整。",
    websiteKnowledgeGlobalPrivacyControl: "Global Privacy Control",
    websiteKnowledgeGlobalPrivacyControlHelp: "向网站发送隐私偏好信号，表明请勿出售或共享您的个人数据。",
    websiteKnowledgePrivacy: "所有调整均在本机完成，不读取网页内容，也不修改系统设置。网站通过浏览器获取您选定的信息。",
    clipboardProtectName: 'Clipboard Protect',
    clipboardProtectDescription: '保护您选中并复制的原文，阻止网站借复制事件擅自夹带链接、署名或推广文字，同时尽量保留原有格式；可编辑区域仍使用网站自身的复制方式。Any Copy 在当前网页生效时，Clipboard Protect 会自动让路。',
    clipboardProtectPrivacy: '仅在复制时于本机处理所选内容，不读取剪贴板中原有的数据，也不保存或上传复制内容。',
    accessControlName: 'Access Control',
    accessControlDescription: '阻止访问所选域名及其全部子域名，以及指定的 IP 地址。规则修订会在匹配页面刷新或再次打开后生效。',
    accessControlBlockedDomainsHeading: '阻止访问的地址',
    accessControlDomainPlaceholder: 'example.com 或 192.0.2.1',
    accessControlEmptyDomains: '尚未设置阻止访问的地址。',
    accessControlInvalidDomain: '请输入有效的域名或 IP 地址。',
    accessControlSubdomainsSuffix: '及其所有子域名',
    accessControlTemporaryVisits: '允许通过插件控制窗口进行单次访问。',
    accessControlAllowVisitTitle: '允许本次访问',
    accessControlPrivacy: 'Access Control 使用本地浏览器网络规则处理您列出的域名和 IP 地址，不会记录访问尝试，也不会上传地址列表。',
    mailtoCaptureName: 'Mailto Capture',
    mailtoCaptureDescription: '拦截邮件链接，避免误触时直接打开系统邮件应用。Mailto Capture 会先在网页内显示简洁的内容预览，列出收件人、抄送与密送地址、主题、正文及链接附带的其他信息，供您按需复制。此外，也支持“tel:”与“sms:”外部协议跳转链接。',
    mailtoCapturePrivacy: 'Mailto Capture 只在本机处理邮件与电话链接，不会记录其中的邮箱地址、电话号码或邮件内容。',
    chineseResponseClaudeName: 'Chinese Response Display Optimization for Claude',
    chineseResponseClaudeDescription: '将 Claude 中文回复中的半角标点转换为对应的全角中文标点，并在中文与英文字母、数字及相关符号之间补充空格。代码、链接、公式和可编辑文本均保持不变。',
    claudeBrowserIdentityHelp: '针对在美国使用 Claude 的场景对浏览器标识的部分信息进行固定化。',
    chineseResponseClaudePrivacy: '本功能仅在受支持的 Claude 与 Anthropic 页面中本地运行。插件不会另行发送或留存回复文本及浏览器标识信息。',
    chineseResponseClaudeOffTitle: '开启 Chinese Response Display Optimization for Claude',
    chineseResponseClaudeOnTitle: 'Chinese Response Display Optimization for Claude 已开启，点击即可关闭',
    chineseResponseClaudeActiveTitle: 'Chinese Response Display Optimization for Claude 已调整此页面，点击即可关闭',
    pageDisplayName: 'Page Display',
    pageDisplayDescription: '通过彼此独立的显示选项调整整个网页的色彩，包括图片和视频。',
    pageDisplayHelpEffects: 'Page Display 可对整个网页应用 Reduce White Point 与 Greyscale，包括其中的图片和视频。',
    pageDisplayHelpRestore: '关闭 Page Display 后，所有网页都会恢复原样，已经选择的显示调整会保留到下次开启。',
    reduceWhitePointName: 'Reduce White Point',
    reduceWhitePointHelp: '降低网页中明亮颜色的强度，让浏览体验更加舒适。',
    reduceWhitePointReductionHeading: '降低强度',
    reduceWhitePointReductionHelp: '调整页面亮度降低的程度。',
    greyscaleName: 'Greyscale',
    greyscaleHelp: '以灰阶方式显示网页。',
    pageDisplayPrivacy: 'Page Display 完全在本地调整页面显示，不会读取或保留网页内容。',
    xhsImageDarkModeName: 'XHS Image Dark Mode',
    xhsImageDarkModeSettingsName: 'XHS Image Dark Mode（测试版）',
    experimentalFeature: '这是一项实验性功能。',
    xhsImageDarkModeDescription: '调暗小红书网页版在页面深色模式下仍然刺眼的文字图片。',
    xhsImageDarkModeScopeDescription: '让笔记和评论中的文字卡片、聊天截图等内容不再那么刺眼，同时保留照片的原始显示。',
    xhsImageDarkModeControlsDescription: '可切换单张图片或整篇笔记的深浅色显示，也可暂停对某个用户主页的调整。',
    xhsImageDarkModeOverrideHeading: '始终启用',
    xhsImageDarkModeOverrideHelp: '即使未检测到页面深色模式，也始终调整符合条件的图片。',
    xhsImageDarkModeControlHeading: '显示图片切换按钮',
    xhsImageDarkModeControlHelp: '展开笔记后，在页码旁显示一个小型按钮。长按可在整篇笔记强制深色与强制浅色之间切换，单击则恢复自动识别；打开评论图片后，会显示独立的单图切换按钮。',
    xhsImageDarkModeOpacityHeading: '按钮透明度',
    xhsImageDarkModeOpacityHelp: '调整图片切换按钮在未操作时的透明度。',
    xhsImageDarkModePrivacy: '图片仅在本机处理，不会上传。页面关闭后会清除临时处理结果。',
    xhsImageDarkModeOffTitle: '在小红书中开启 XHS Image Dark Mode',
    xhsImageDarkModeWaitingTitle: 'XHS Image Dark Mode 已开启，正在等待页面深色模式',
    xhsImageDarkModeActiveTitle: 'XHS Image Dark Mode 正在处理图片，点击即可关闭',
    biliDailyLoginName: 'Bili Daily Login',
    adMarshalName: 'Ad Marshal',
    adMarshalDescription: '阻止管制网站中的广告、上报和跟踪组件反复重连。Ad Marshal 会使用轻量的专用规则，从源头阻止已知加载器和请求循环，并隐藏相关广告元素。',
    adMarshalManagedSitesHeading: '管制网站',
    adMarshalTencentNews: 'news.qq.com（包括 www.qq.com）',
    adMarshalZhihu: 'zhihu.com 及其子域名',
    adMarshalPrivacy: 'Ad Marshal 仅在您选择的网站中运行，全部处理均在本地完成，不会记录您的浏览活动。',
    satellitesHelpHeading: '关于 Satellites',
    satellitesHelpIntro: 'Satellites 收纳无需常驻控制窗口的小功能。各项功能互不干扰，网站专用的控制按钮也只会在适用页面出现。',
    satellitesOverviewHelp: '按需开启各项相互独立的小功能。',
    disabledInIncognito: '已在无痕模式下停用',
    disabledByDefaultInIncognito: '在无痕模式下默认停用。',
    biliDailyLoginDescription: '哔哩哔哩会向完成每日登录的账号发放一枚硬币。Chrome 可以运行时，Bili Daily Login 会自动完成当天的登录。',
    biliDailyLoginPrivacyHeading: '隐私',
    biliDailyLoginPrivacy: 'Bili Daily Login 不会监测您是否或何时访问哔哩哔哩。它只会在电脑已唤醒且 Chrome 正在运行时调用哔哩哔哩账号服务，并使用 Chrome 中已有的登录状态，不会读取或保存密码。最近一次完成日期和少量日程数据会用于避免重复执行。',
    privacyHeading: '隐私',
    nativePrivacy: 'Native Scroll 完全在本地运行，不会发送浏览数据。网站规则仅包含您选择的主机名或 IP 地址。',
    autoplayPrivacy: 'No Autoplay 完全在本地运行，不会发送浏览数据。网站规则仅包含您选择的主机名或 IP 地址。',
    anyCopyPrivacy: 'Any Copy 与 Any Copy 强力模式完全在本地运行，不会发送复制内容或浏览数据。网站规则仅包含您选择的主机名或 IP 地址，强力模式的当前标签页状态只在本次浏览器会话中保留。',
    allSettingsName: '全部设置',
    allSettingsIntro: '在一个页面中进入 Cosmic Gemini 各项功能的设置。',
    allSettingsHelpHeading: '设置导航',
    allSettingsHelp: '请选择需要设置的功能。每项功能都会在自己的页面中管理操作选项和网站规则。',
    allSettingsNativeDescription: '设置滚动保护和网站规则。',
    allSettingsAutoplayDescription: '设置媒体拦截和声音自动播放权限。',
    allSettingsAnyCopyDescription: '管理 Any Copy 网站，并了解 Any Copy 强力模式在当前标签页中的使用方式。',
    allSettingsImageDescription: '设置图片工作区和默认下载方式。',
    allSettingsVideoDescription: '设置视频画质和下载方式。',
    allSettingsPageDisplayDescription: '调整网页的亮度和色彩。',
    allSettingsSatellitesDescription: '管理各项辅助小功能。',
    resetAllSettingsHeading: '重置设置',
    resetAllSettingsHelp: '将各项功能设置和网站规则恢复为默认状态。',
    resetAllSettingsAction: '重置所有设置',
    resetAllSettingsConfirmHeading: '重置所有设置？',
    resetAllSettingsConfirmHelp: '此操作会恢复全部默认设置、移除已保存的网站规则，并结束当前的临时任务。已下载的文件不受影响。',
    cancel: '取消',
    reset: '重置',
    version: '版本 {version}',
    unavailable: 'Cosmic Gemini 暂时无法更新设置。'
  }
};
