import { createHash } from 'node:crypto';
import { readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const SOURCE_URL = 'https://publicsuffix.org/list/public_suffix_list.dat';
const PRIVATE_GROUPS = Object.freeze([
  'CentralNic',
  'Cloudflare, Inc.',
  'EU.org',
  'GitHub, Inc.',
  'GitLab, Inc.'
]);
// Broad category reference for PSL PRIVATE DOMAINS-sector geographic eTLD rules.
// Category source: https://geotld.group/geotld/
// Keep this as a category, rather than selecting geographic namespaces for individual regions.
const PSL_PRIVATE_DOMAINS_SECTOR_GEOGRAPHIC_ETLD_GROUPS = Object.freeze([
  'Coordination Center for TLD RU and XN--P1AI'
]);
const PSL_PRIVATE_DOMAINS_SECTOR_GEOGRAPHIC_ETLD_TLDS = Object.freeze([
  'abudhabi', 'africa', 'alsace', 'amsterdam', 'arab', 'barcelona', 'bayern', 'berlin',
  'boston', 'brussels', 'budapest', 'bzh', 'capetown', 'cat', 'cologne', 'corsica',
  'cymru', 'desi', 'dubai', 'durban', 'eus', 'frl', 'gal', 'gent', 'hamburg', 'helsinki',
  'irish', 'ist', 'istanbul', 'joburg', 'koeln', 'krd', 'kyoto', 'lat', 'london', 'madrid',
  'melbourne', 'miami', 'moscow', 'nagoya', 'nrw', 'nyc', 'okinawa', 'osaka', 'paris',
  'quebec', 'rio', 'ruhr', 'ryukyu', 'saarland', 'scot', 'stockholm', 'swiss', 'sydney',
  'taipei', 'tatar', 'tirol', 'tokyo', 'vegas', 'vlaanderen', 'wales', 'wien', 'yokohama',
  'zuerich', 'москва', 'ابوظبي', 'عرب', '广州', '佛山', '广东', 'guangdong', 'fohsan',
  'guangzhou'
]);
const project = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const destination = resolve(project, 'extension/vendor/publicsuffix/etld.js');

function section(text, begin, end) {
  const start = text.indexOf(begin);
  const finish = text.indexOf(end);
  if (start < 0 || finish <= start) throw new Error(`Missing PSL section: ${begin}`);
  return text.slice(start + begin.length, finish).trim();
}

function rules(block) {
  return block.split(/\r?\n/)
    .map(line => line.trim())
    .filter(line => line && !line.startsWith('//'));
}

function privateGroupRules(privateSection, group) {
  const blocks = privateSection.split(/(?:\r?\n){2,}/);
  const prefix = `// ${group}`;
  const block = blocks.find(candidate => candidate.trimStart().startsWith(prefix));
  if (!block) throw new Error(`Missing requested PSL PRIVATE group: ${group}`);
  return rules(block);
}

function finalLabel(rule) {
  const ordinary = rule.replace(/^!|^\*\./, '');
  return ordinary.slice(ordinary.lastIndexOf('.') + 1).toLowerCase();
}

async function sourceText() {
  const input = process.argv[2];
  if (input) return readFile(resolve(input), 'utf8');
  const response = await fetch(SOURCE_URL, { cache: 'no-store' });
  if (!response.ok) throw new Error(`PSL download failed: HTTP ${response.status}`);
  return response.text();
}

const text = await sourceText();
const icannSection = section(text, '// ===BEGIN ICANN DOMAINS===', '// ===END ICANN DOMAINS===');
const privateSection = section(text, '// ===BEGIN PRIVATE DOMAINS===', '// ===END PRIVATE DOMAINS===');
const icannRules = rules(icannSection);
const selectedPrivateRules = PRIVATE_GROUPS.flatMap(group => privateGroupRules(privateSection, group));
const pslPrivateDomainsSectorGeographicEtldRules = [...new Set([
  ...PSL_PRIVATE_DOMAINS_SECTOR_GEOGRAPHIC_ETLD_GROUPS
    .flatMap(group => privateGroupRules(privateSection, group)),
  ...rules(privateSection)
    .filter(rule => PSL_PRIVATE_DOMAINS_SECTOR_GEOGRAPHIC_ETLD_TLDS.includes(finalLabel(rule)))
])];
const privateRules = [...new Set([...selectedPrivateRules, ...pslPrivateDomainsSectorGeographicEtldRules])];
const etld = [...new Set([...icannRules, ...privateRules])];
const version = text.match(/^\/\/ VERSION:\s*(.+)$/m)?.[1] || '';
const commit = text.match(/^\/\/ COMMIT:\s*(.+)$/m)?.[1] || '';
if (!version || !commit || icannRules.length < 1_000) throw new Error('The PSL snapshot is incomplete.');

const output = `// Generated by scripts/update-etld.mjs from the Public Suffix List.\n`
  + `// The generated data remains available under Mozilla Public License 2.0.\n`
  + `// Do not edit this file directly.\n\n`
  + `export const etldMetadata = Object.freeze(${JSON.stringify({
    source: SOURCE_URL,
    version,
    commit,
    sha256: createHash('sha256').update(text).digest('hex'),
    icannRuleCount: icannRules.length,
    privateExceptionRuleCount: privateRules.length,
    pslPrivateDomainsSectorGeographicEtldRuleCount: pslPrivateDomainsSectorGeographicEtldRules.length,
    ruleCount: etld.length,
    privateGroups: PRIVATE_GROUPS
  }, null, 2)});\n\n`
  + `export const etld = Object.freeze(${JSON.stringify(etld, null, 2)});\n`;

await writeFile(destination, output);
await import('./build-stay-site-key.mjs');
console.log(`Wrote ${etld.length} etld rules (${icannRules.length} ICANN + ${privateRules.length} selected PRIVATE).`);
