import { createHash } from 'node:crypto';
import { readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const SOURCE_URL = 'https://publicsuffix.org/list/public_suffix_list.dat';
const PRIVATE_GROUPS = Object.freeze([
  'CentralNic',
  'Cloudflare, Inc.',
  'Coordination Center for TLD RU and XN--P1AI',
  'EU.org',
  'GitHub, Inc.',
  'GitLab, Inc.'
]);
const GEOGRAPHIC_PRIVATE_TLDS = Object.freeze(['krd', 'scot']);
const project = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const destination = resolve(project, 'extension/vendor/publicsuffix/etld.js');

function section(text, begin, end) {
  const start = text.indexOf(begin);
  const finish = text.indexOf(end);
  if (start < 0 || finish <= start) throw new Error(`Missing PSL section: ${begin}`);
  return text.slice(start + begin.length, finish).trim();
}

function rules(block) {
  return block.split(/\r?\n/)
    .map(line => line.trim())
    .filter(line => line && !line.startsWith('//'));
}

function privateGroupRules(privateSection, group) {
  const blocks = privateSection.split(/(?:\r?\n){2,}/);
  const prefix = `// ${group}`;
  const block = blocks.find(candidate => candidate.trimStart().startsWith(prefix));
  if (!block) throw new Error(`Missing requested PSL PRIVATE group: ${group}`);
  return rules(block);
}

function finalLabel(rule) {
  const ordinary = rule.replace(/^!|^\*\./, '');
  return ordinary.slice(ordinary.lastIndexOf('.') + 1).toLowerCase();
}

async function sourceText() {
  const input = process.argv[2];
  if (input) return readFile(resolve(input), 'utf8');
  const response = await fetch(SOURCE_URL, { cache: 'no-store' });
  if (!response.ok) throw new Error(`PSL download failed: HTTP ${response.status}`);
  return response.text();
}

const text = await sourceText();
const icannSection = section(text, '// ===BEGIN ICANN DOMAINS===', '// ===END ICANN DOMAINS===');
const privateSection = section(text, '// ===BEGIN PRIVATE DOMAINS===', '// ===END PRIVATE DOMAINS===');
const icannRules = rules(icannSection);
const selectedPrivateRules = PRIVATE_GROUPS.flatMap(group => privateGroupRules(privateSection, group));
const geographicPrivateRules = rules(privateSection)
  .filter(rule => GEOGRAPHIC_PRIVATE_TLDS.includes(finalLabel(rule)));
const privateRules = [...new Set([...selectedPrivateRules, ...geographicPrivateRules])];
const etld = [...new Set([...icannRules, ...privateRules])];
const version = text.match(/^\/\/ VERSION:\s*(.+)$/m)?.[1] || '';
const commit = text.match(/^\/\/ COMMIT:\s*(.+)$/m)?.[1] || '';
if (!version || !commit || icannRules.length < 1_000) throw new Error('The PSL snapshot is incomplete.');

const output = `// Generated by scripts/update-etld.mjs from the Public Suffix List.\n`
  + `// The generated data remains available under Mozilla Public License 2.0.\n`
  + `// Do not edit this file directly.\n\n`
  + `export const etldMetadata = Object.freeze(${JSON.stringify({
    source: SOURCE_URL,
    version,
    commit,
    sha256: createHash('sha256').update(text).digest('hex'),
    icannRuleCount: icannRules.length,
    privateExceptionRuleCount: privateRules.length,
    ruleCount: etld.length,
    privateGroups: PRIVATE_GROUPS,
    geographicPrivateTlds: GEOGRAPHIC_PRIVATE_TLDS
  }, null, 2)});\n\n`
  + `export const etld = Object.freeze(${JSON.stringify(etld, null, 2)});\n`;

await writeFile(destination, output);
console.log(`Wrote ${etld.length} etld rules (${icannRules.length} ICANN + ${privateRules.length} selected PRIVATE).`);
